/* CVS $Id: $ */
package org.doremus.ontology;
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;

/**
 * Vocabulary definitions from https://raw.githubusercontent.com/DOREMUS-ANR/doremus-ontology/master/FRBRoo-v2.4-Biblissima-2016-04-17.owl
 * @author Auto-generated by schemagen on 17 giu 2016 14:47
 */
public class CIDOC {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://erlangen-crm.org/current/";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "This is a version of the FRBRoo 2.4 specifications in OWL that is based on the structure of the current efrbroo and the text file (odt), realised by Biblissima April 2O16";

    public static final ObjectProperty P100_was_death_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P100_was_death_of" );

    public static final ObjectProperty P102_has_title = m_model.createObjectProperty( "http://erlangen-crm.org/current/P102_has_title" );

    public static final ObjectProperty P103_was_intended_for = m_model.createObjectProperty( "http://erlangen-crm.org/current/P103_was_intended_for" );

    public static final ObjectProperty P104_is_subject_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P104_is_subject_to" );

    public static final ObjectProperty P105_right_held_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P105_right_held_by" );

    public static final ObjectProperty P106_is_composed_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P106_is_composed_of" );

    public static final ObjectProperty P107_has_current_or_former_member = m_model.createObjectProperty( "http://erlangen-crm.org/current/P107_has_current_or_former_member" );

    public static final ObjectProperty P108_has_produced = m_model.createObjectProperty( "http://erlangen-crm.org/current/P108_has_produced" );

    public static final ObjectProperty P125_used_object_of_type = m_model.createObjectProperty( "http://erlangen-crm.org/current/P125_used_object_of_type" );

    public static final ObjectProperty P127_has_broader_term = m_model.createObjectProperty( "http://erlangen-crm.org/current/P127_has_broader_term" );

    public static final ObjectProperty P128_carries = m_model.createObjectProperty( "http://erlangen-crm.org/current/P128_carries" );

    public static final ObjectProperty P129_is_about = m_model.createObjectProperty( "http://erlangen-crm.org/current/P129_is_about" );

    public static final ObjectProperty P12_occurred_in_the_presence_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P12_occurred_in_the_presence_of" );

    public static final ObjectProperty P130_shows_features_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P130_shows_features_of" );

    public static final ObjectProperty P131_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P131_is_identified_by" );

    public static final ObjectProperty P138_represents = m_model.createObjectProperty( "http://erlangen-crm.org/current/P138_represents" );

    public static final ObjectProperty P140_assigned_attribute_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P140_assigned_attribute_to" );

    public static final ObjectProperty P141_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/current/P141_assigned" );

    public static final ObjectProperty P142_used_constituent = m_model.createObjectProperty( "http://erlangen-crm.org/current/P142_used_constituent" );

    public static final ObjectProperty P148_has_component = m_model.createObjectProperty( "http://erlangen-crm.org/current/P148_has_component" );

    public static final ObjectProperty P14_carried_out_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P14_carried_out_by" );

    public static final ObjectProperty P151_was_formed_from = m_model.createObjectProperty( "http://erlangen-crm.org/current/P151_was_formed_from" );

    public static final ObjectProperty P15_was_influenced_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P15_was_influenced_by" );

    public static final ObjectProperty P165_incorporates = m_model.createObjectProperty( "http://erlangen-crm.org/current/P165_incorporates" );

    public static final ObjectProperty P16_used_specific_object = m_model.createObjectProperty( "http://erlangen-crm.org/current/P16_used_specific_object" );

    public static final ObjectProperty P1_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P1_is_identified_by" );

    public static final ObjectProperty P2_has_type = m_model.createObjectProperty( "http://erlangen-crm.org/current/P2_has_type" );

    public static final ObjectProperty P31_has_modified = m_model.createObjectProperty( "http://erlangen-crm.org/current/P31_has_modified" );

    public static final ObjectProperty P33_used_specific_technique = m_model.createObjectProperty( "http://erlangen-crm.org/current/P33_used_specific_technique" );

    public static final ObjectProperty P37_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/current/P37_assigned" );

    public static final ObjectProperty P3_has_note = m_model.createObjectProperty( "http://erlangen-crm.org/current/P3_has_note" );

    public static final ObjectProperty P43_has_dimension = m_model.createObjectProperty( "http://erlangen-crm.org/current/P43_has_dimension" );

    public static final ObjectProperty P44_has_condition = m_model.createObjectProperty( "http://erlangen-crm.org/current/P44_has_condition" );

    public static final ObjectProperty P45_consists_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P45_consists_of" );

    public static final ObjectProperty P46_is_composed_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P46_is_composed_of" );

    public static final ObjectProperty P49_has_former_or_current_keeper = m_model.createObjectProperty( "http://erlangen-crm.org/current/P49_has_former_or_current_keeper" );

    public static final ObjectProperty P4_has_time_span = m_model.createObjectProperty( "http://erlangen-crm.org/current/P4_has_time-span" );

    public static final ObjectProperty P50_has_current_keeper = m_model.createObjectProperty( "http://erlangen-crm.org/current/P50_has_current_keeper" );

    public static final ObjectProperty P51_has_former_or_current_owner = m_model.createObjectProperty( "http://erlangen-crm.org/current/P51_has_former_or_current_owner" );

    public static final ObjectProperty P57_has_number_of_parts = m_model.createObjectProperty( "http://erlangen-crm.org/current/P57_has_number_of_parts" );

    public static final ObjectProperty P59_has_section = m_model.createObjectProperty( "http://erlangen-crm.org/current/P59_has_section" );

    public static final ObjectProperty P65_shows_visual_item = m_model.createObjectProperty( "http://erlangen-crm.org/current/P65_shows_visual_item" );

    public static final ObjectProperty P67_refers_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P67_refers_to" );

    public static final ObjectProperty P69_has_association_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P69_has_association_with" );

    public static final ObjectProperty P71_lists = m_model.createObjectProperty( "http://erlangen-crm.org/current/P71_lists" );

    public static final ObjectProperty P72_has_language = m_model.createObjectProperty( "http://erlangen-crm.org/current/P72_has_language" );

    public static final ObjectProperty P74_has_current_or_former_residence = m_model.createObjectProperty( "http://erlangen-crm.org/current/P74_has_current_or_former_residence" );

    public static final ObjectProperty P75_possesses = m_model.createObjectProperty( "http://erlangen-crm.org/current/P75_possesses" );

    public static final ObjectProperty P78_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P78_is_identified_by" );

    public static final ObjectProperty P7_took_place_at = m_model.createObjectProperty( "http://erlangen-crm.org/current/P7_took_place_at" );

    public static final ObjectProperty P82_at_some_time_within = m_model.createObjectProperty( "http://erlangen-crm.org/current/P82_at_some_time_within" );

    public static final ObjectProperty P87_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P87_is_identified_by" );

    public static final ObjectProperty P91_has_unit = m_model.createObjectProperty( "http://erlangen-crm.org/current/P91_has_unit" );

    public static final ObjectProperty P93_took_out_of_existence = m_model.createObjectProperty( "http://erlangen-crm.org/current/P93_took_out_of_existence" );

    public static final ObjectProperty P94_has_created = m_model.createObjectProperty( "http://erlangen-crm.org/current/P94_has_created" );

    public static final ObjectProperty P95_has_formed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P95_has_formed" );

    public static final ObjectProperty P98_brought_into_life = m_model.createObjectProperty( "http://erlangen-crm.org/current/P98_brought_into_life" );

    public static final ObjectProperty P9_consists_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P9_consists_of" );

    public static final OntClass E11_Modification = m_model.createClass( "http://erlangen-crm.org/current/E11_Modification" );

    public static final OntClass E12_Production = m_model.createClass( "http://erlangen-crm.org/current/E12_Production" );

    public static final OntClass E13_Attribute_Assignment = m_model.createClass( "http://erlangen-crm.org/current/E13_Attribute_Assignment" );

    public static final OntClass E15_Identifier_Assignment = m_model.createClass( "http://erlangen-crm.org/current/E15_Identifier_Assignment" );

    public static final OntClass E18_Physical_Thing = m_model.createClass( "http://erlangen-crm.org/current/E18_Physical_Thing" );

    public static final OntClass E19_Physical_Object = m_model.createClass( "http://erlangen-crm.org/current/E19_Physical_Object" );

    public static final OntClass E1_CRM_Entity = m_model.createClass( "http://erlangen-crm.org/current/E1_CRM_Entity" );

    public static final OntClass E21_Person = m_model.createClass( "http://erlangen-crm.org/current/E21_Person" );

    public static final OntClass E22_Man_Made_Object = m_model.createClass( "http://erlangen-crm.org/current/E22_Man-Made_Object" );

    public static final OntClass E24_Physical_Man_Made_Thing = m_model.createClass( "http://erlangen-crm.org/current/E24_Physical_Man-Made_Thing" );

    public static final OntClass E25_Man_Made_Feature = m_model.createClass( "http://erlangen-crm.org/current/E25_Man-Made_Feature" );

    public static final OntClass E26_Physical_Feature = m_model.createClass( "http://erlangen-crm.org/current/E26_Physical_Feature" );

    public static final OntClass E27_Site = m_model.createClass( "http://erlangen-crm.org/current/E27_Site" );

    public static final OntClass E28_Conceptual_Object = m_model.createClass( "http://erlangen-crm.org/current/E28_Conceptual_Object" );

    public static final OntClass E29_Design_or_Procedure = m_model.createClass( "http://erlangen-crm.org/current/E29_Design_or_Procedure" );

    public static final OntClass E2_Temporal_Entity = m_model.createClass( "http://erlangen-crm.org/current/E2_Temporal_Entity" );

    public static final OntClass E30_Right = m_model.createClass( "http://erlangen-crm.org/current/E30_Right" );

    public static final OntClass E31_Document = m_model.createClass( "http://erlangen-crm.org/current/E31_Document" );

    public static final OntClass E32_Authority_Document = m_model.createClass( "http://erlangen-crm.org/current/E32_Authority_Document" );

    public static final OntClass E33_Linguistic_Object = m_model.createClass( "http://erlangen-crm.org/current/E33_Linguistic_Object" );

    public static final OntClass E35_Title = m_model.createClass( "http://erlangen-crm.org/current/E35_Title" );

    public static final OntClass E36_Visual_Item = m_model.createClass( "http://erlangen-crm.org/current/E36_Visual_Item" );

    public static final OntClass E37_Mark = m_model.createClass( "http://erlangen-crm.org/current/E37_Mark" );

    public static final OntClass E39_Actor = m_model.createClass( "http://erlangen-crm.org/current/E39_Actor" );

    public static final OntClass E3_Condition_State = m_model.createClass( "http://erlangen-crm.org/current/E3_Condition_State" );

    public static final OntClass E40_Legal_Body = m_model.createClass( "http://erlangen-crm.org/current/E40_Legal_Body" );

    public static final OntClass E41_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E41_Appellation" );

    public static final OntClass E42_Identifier = m_model.createClass( "http://erlangen-crm.org/current/E42_Identifier" );

    public static final OntClass E44_Place_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E44_Place_Appellation" );

    public static final OntClass E47_Spatial_Coordinates = m_model.createClass( "http://erlangen-crm.org/current/E47_Spatial_Coordinates" );

    public static final OntClass E49_Time_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E49_Time_Appellation" );

    public static final OntClass E4_Period = m_model.createClass( "http://erlangen-crm.org/current/E4_Period" );

    public static final OntClass E50_Date = m_model.createClass( "http://erlangen-crm.org/current/E50_Date" );

    public static final OntClass E52_Time_Span = m_model.createClass( "http://erlangen-crm.org/current/E52_Time-Span" );

    public static final OntClass E53_Place = m_model.createClass( "http://erlangen-crm.org/current/E53_Place" );

    public static final OntClass E54_Dimension = m_model.createClass( "http://erlangen-crm.org/current/E54_Dimension" );

    public static final OntClass E55_Type = m_model.createClass( "http://erlangen-crm.org/current/E55_Type" );

    public static final OntClass E56_Language = m_model.createClass( "http://erlangen-crm.org/current/E56_Language" );

    public static final OntClass E57_Material = m_model.createClass( "http://erlangen-crm.org/current/E57_Material" );

    public static final OntClass E59_Primitive_Value = m_model.createClass( "http://erlangen-crm.org/current/E59_Primitive_Value" );

    public static final OntClass E5_Event = m_model.createClass( "http://erlangen-crm.org/current/E5_Event" );

    public static final OntClass E60_Number = m_model.createClass( "http://erlangen-crm.org/current/E60_Number" );

    public static final OntClass E61_Time_Primitive = m_model.createClass( "http://erlangen-crm.org/current/E61_Time_Primitive" );

    public static final OntClass E62_String = m_model.createClass( "http://erlangen-crm.org/current/E62_String" );

    public static final OntClass E63_Beginning_of_Existence = m_model.createClass( "http://erlangen-crm.org/current/E63_Beginning_of_Existence" );

    public static final OntClass E64_End_of_Existence = m_model.createClass( "http://erlangen-crm.org/current/E64_End_of_Existence" );

    public static final OntClass E65_Creation = m_model.createClass( "http://erlangen-crm.org/current/E65_Creation" );

    public static final OntClass E66_Formation = m_model.createClass( "http://erlangen-crm.org/current/E66_Formation" );

    public static final OntClass E67_Birth = m_model.createClass( "http://erlangen-crm.org/current/E67_Birth" );

    public static final OntClass E69_Death = m_model.createClass( "http://erlangen-crm.org/current/E69_Death" );

    public static final OntClass E70_Thing = m_model.createClass( "http://erlangen-crm.org/current/E70_Thing" );

    public static final OntClass E71_Man_Made_Thing = m_model.createClass( "http://erlangen-crm.org/current/E71_Man-Made_Thing" );

    public static final OntClass E72_Legal_Object = m_model.createClass( "http://erlangen-crm.org/current/E72_Legal_Object" );

    public static final OntClass E73_Information_Object = m_model.createClass( "http://erlangen-crm.org/current/E73_Information_Object" );

    public static final OntClass E74_Group = m_model.createClass( "http://erlangen-crm.org/current/E74_Group" );

    public static final OntClass E77_Persistent_Item = m_model.createClass( "http://erlangen-crm.org/current/E77_Persistent_Item" );

    public static final OntClass E7_Activity = m_model.createClass( "http://erlangen-crm.org/current/E7_Activity" );

    public static final OntClass E82_Actor_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E82_Actor_Appellation" );

    public static final OntClass E84_Information_Carrier = m_model.createClass( "http://erlangen-crm.org/current/E84_Information_Carrier" );

    public static final OntClass E89_Propositional_Object = m_model.createClass( "http://erlangen-crm.org/current/E89_Propositional_Object" );

    public static final OntClass E90_Symbolic_Object = m_model.createClass( "http://erlangen-crm.org/current/E90_Symbolic_Object" );

}
