/* CVS $Id: $ */
package org.doremus.ontology; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from http://erlangen-crm.org/current/ 
 * @author Auto-generated by schemagen on 15 Jan 2018 10:57 
 */
public class CIDOC {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://erlangen-crm.org/current/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "ECRM 160714 / CIDOC-CRM 6.2.1";
    
    public static final ObjectProperty P100_was_death_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P100_was_death_of" );
    
    public static final ObjectProperty P100i_died_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P100i_died_in" );
    
    public static final ObjectProperty P101_had_as_general_use = m_model.createObjectProperty( "http://erlangen-crm.org/current/P101_had_as_general_use" );
    
    public static final ObjectProperty P101i_was_use_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P101i_was_use_of" );
    
    public static final ObjectProperty P102_has_title = m_model.createObjectProperty( "http://erlangen-crm.org/current/P102_has_title" );
    
    public static final ObjectProperty P102i_is_title_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P102i_is_title_of" );
    
    public static final ObjectProperty P103_was_intended_for = m_model.createObjectProperty( "http://erlangen-crm.org/current/P103_was_intended_for" );
    
    public static final ObjectProperty P103i_was_intention_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P103i_was_intention_of" );
    
    public static final ObjectProperty P104_is_subject_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P104_is_subject_to" );
    
    public static final ObjectProperty P104i_applies_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P104i_applies_to" );
    
    public static final ObjectProperty P105_right_held_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P105_right_held_by" );
    
    public static final ObjectProperty P105i_has_right_on = m_model.createObjectProperty( "http://erlangen-crm.org/current/P105i_has_right_on" );
    
    public static final ObjectProperty P106_is_composed_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P106_is_composed_of" );
    
    public static final ObjectProperty P106i_forms_part_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P106i_forms_part_of" );
    
    public static final ObjectProperty P107_has_current_or_former_member = m_model.createObjectProperty( "http://erlangen-crm.org/current/P107_has_current_or_former_member" );
    
    public static final ObjectProperty P107i_is_current_or_former_member_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P107i_is_current_or_former_member_of" );
    
    public static final ObjectProperty P108_has_produced = m_model.createObjectProperty( "http://erlangen-crm.org/current/P108_has_produced" );
    
    public static final ObjectProperty P108i_was_produced_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P108i_was_produced_by" );
    
    public static final ObjectProperty P109_has_current_or_former_curator = m_model.createObjectProperty( "http://erlangen-crm.org/current/P109_has_current_or_former_curator" );
    
    public static final ObjectProperty P109i_is_current_or_former_curator_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P109i_is_current_or_former_curator_of" );
    
    public static final ObjectProperty P10_falls_within = m_model.createObjectProperty( "http://erlangen-crm.org/current/P10_falls_within" );
    
    public static final ObjectProperty P10i_contains = m_model.createObjectProperty( "http://erlangen-crm.org/current/P10i_contains" );
    
    public static final ObjectProperty P110_augmented = m_model.createObjectProperty( "http://erlangen-crm.org/current/P110_augmented" );
    
    public static final ObjectProperty P110i_was_augmented_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P110i_was_augmented_by" );
    
    public static final ObjectProperty P111_added = m_model.createObjectProperty( "http://erlangen-crm.org/current/P111_added" );
    
    public static final ObjectProperty P111i_was_added_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P111i_was_added_by" );
    
    public static final ObjectProperty P112_diminished = m_model.createObjectProperty( "http://erlangen-crm.org/current/P112_diminished" );
    
    public static final ObjectProperty P112i_was_diminished_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P112i_was_diminished_by" );
    
    public static final ObjectProperty P113_removed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P113_removed" );
    
    public static final ObjectProperty P113i_was_removed_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P113i_was_removed_by" );
    
    public static final ObjectProperty P114_is_equal_in_time_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P114_is_equal_in_time_to" );
    
    public static final ObjectProperty P115_finishes = m_model.createObjectProperty( "http://erlangen-crm.org/current/P115_finishes" );
    
    public static final ObjectProperty P115i_is_finished_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P115i_is_finished_by" );
    
    public static final ObjectProperty P116_starts = m_model.createObjectProperty( "http://erlangen-crm.org/current/P116_starts" );
    
    public static final ObjectProperty P116i_is_started_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P116i_is_started_by" );
    
    public static final ObjectProperty P117_occurs_during = m_model.createObjectProperty( "http://erlangen-crm.org/current/P117_occurs_during" );
    
    public static final ObjectProperty P117i_includes = m_model.createObjectProperty( "http://erlangen-crm.org/current/P117i_includes" );
    
    public static final ObjectProperty P118_overlaps_in_time_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P118_overlaps_in_time_with" );
    
    public static final ObjectProperty P118i_is_overlapped_in_time_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P118i_is_overlapped_in_time_by" );
    
    public static final ObjectProperty P119_meets_in_time_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P119_meets_in_time_with" );
    
    public static final ObjectProperty P119i_is_met_in_time_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P119i_is_met_in_time_by" );
    
    public static final ObjectProperty P11_had_participant = m_model.createObjectProperty( "http://erlangen-crm.org/current/P11_had_participant" );
    
    public static final ObjectProperty P11i_participated_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P11i_participated_in" );
    
    public static final ObjectProperty P120_occurs_before = m_model.createObjectProperty( "http://erlangen-crm.org/current/P120_occurs_before" );
    
    public static final ObjectProperty P120i_occurs_after = m_model.createObjectProperty( "http://erlangen-crm.org/current/P120i_occurs_after" );
    
    public static final ObjectProperty P121_overlaps_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P121_overlaps_with" );
    
    public static final ObjectProperty P122_borders_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P122_borders_with" );
    
    public static final ObjectProperty P123_resulted_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P123_resulted_in" );
    
    public static final ObjectProperty P123i_resulted_from = m_model.createObjectProperty( "http://erlangen-crm.org/current/P123i_resulted_from" );
    
    public static final ObjectProperty P124_transformed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P124_transformed" );
    
    public static final ObjectProperty P124i_was_transformed_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P124i_was_transformed_by" );
    
    public static final ObjectProperty P125_used_object_of_type = m_model.createObjectProperty( "http://erlangen-crm.org/current/P125_used_object_of_type" );
    
    public static final ObjectProperty P125i_was_type_of_object_used_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P125i_was_type_of_object_used_in" );
    
    public static final ObjectProperty P126_employed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P126_employed" );
    
    public static final ObjectProperty P126i_was_employed_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P126i_was_employed_in" );
    
    public static final ObjectProperty P127_has_broader_term = m_model.createObjectProperty( "http://erlangen-crm.org/current/P127_has_broader_term" );
    
    public static final ObjectProperty P127i_has_narrower_term = m_model.createObjectProperty( "http://erlangen-crm.org/current/P127i_has_narrower_term" );
    
    public static final ObjectProperty P128_carries = m_model.createObjectProperty( "http://erlangen-crm.org/current/P128_carries" );
    
    public static final ObjectProperty P128i_is_carried_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P128i_is_carried_by" );
    
    public static final ObjectProperty P129_is_about = m_model.createObjectProperty( "http://erlangen-crm.org/current/P129_is_about" );
    
    public static final ObjectProperty P129i_is_subject_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P129i_is_subject_of" );
    
    public static final ObjectProperty P12_occurred_in_the_presence_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P12_occurred_in_the_presence_of" );
    
    public static final ObjectProperty P12i_was_present_at = m_model.createObjectProperty( "http://erlangen-crm.org/current/P12i_was_present_at" );
    
    public static final ObjectProperty P130_shows_features_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P130_shows_features_of" );
    
    public static final ObjectProperty P130i_features_are_also_found_on = m_model.createObjectProperty( "http://erlangen-crm.org/current/P130i_features_are_also_found_on" );
    
    public static final ObjectProperty P131_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P131_is_identified_by" );
    
    public static final ObjectProperty P131i_identifies = m_model.createObjectProperty( "http://erlangen-crm.org/current/P131i_identifies" );
    
    public static final ObjectProperty P132_overlaps_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P132_overlaps_with" );
    
    public static final ObjectProperty P133_is_separated_from = m_model.createObjectProperty( "http://erlangen-crm.org/current/P133_is_separated_from" );
    
    public static final ObjectProperty P134_continued = m_model.createObjectProperty( "http://erlangen-crm.org/current/P134_continued" );
    
    public static final ObjectProperty P134i_was_continued_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P134i_was_continued_by" );
    
    public static final ObjectProperty P135_created_type = m_model.createObjectProperty( "http://erlangen-crm.org/current/P135_created_type" );
    
    public static final ObjectProperty P135i_was_created_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P135i_was_created_by" );
    
    public static final ObjectProperty P136_was_based_on = m_model.createObjectProperty( "http://erlangen-crm.org/current/P136_was_based_on" );
    
    public static final ObjectProperty P136i_supported_type_creation = m_model.createObjectProperty( "http://erlangen-crm.org/current/P136i_supported_type_creation" );
    
    public static final ObjectProperty P137_exemplifies = m_model.createObjectProperty( "http://erlangen-crm.org/current/P137_exemplifies" );
    
    public static final ObjectProperty P137i_is_exemplified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P137i_is_exemplified_by" );
    
    public static final ObjectProperty P138_represents = m_model.createObjectProperty( "http://erlangen-crm.org/current/P138_represents" );
    
    public static final ObjectProperty P138i_has_representation = m_model.createObjectProperty( "http://erlangen-crm.org/current/P138i_has_representation" );
    
    public static final ObjectProperty P139_has_alternative_form = m_model.createObjectProperty( "http://erlangen-crm.org/current/P139_has_alternative_form" );
    
    public static final ObjectProperty P13_destroyed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P13_destroyed" );
    
    public static final ObjectProperty P13i_was_destroyed_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P13i_was_destroyed_by" );
    
    public static final ObjectProperty P140_assigned_attribute_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P140_assigned_attribute_to" );
    
    public static final ObjectProperty P140i_was_attributed_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P140i_was_attributed_by" );
    
    public static final ObjectProperty P141_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/current/P141_assigned" );
    
    public static final ObjectProperty P141i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P141i_was_assigned_by" );
    
    public static final ObjectProperty P142_used_constituent = m_model.createObjectProperty( "http://erlangen-crm.org/current/P142_used_constituent" );
    
    public static final ObjectProperty P142i_was_used_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P142i_was_used_in" );
    
    public static final ObjectProperty P143_joined = m_model.createObjectProperty( "http://erlangen-crm.org/current/P143_joined" );
    
    public static final ObjectProperty P143i_was_joined_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P143i_was_joined_by" );
    
    public static final ObjectProperty P144_joined_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P144_joined_with" );
    
    public static final ObjectProperty P144i_gained_member_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P144i_gained_member_by" );
    
    public static final ObjectProperty P145_separated = m_model.createObjectProperty( "http://erlangen-crm.org/current/P145_separated" );
    
    public static final ObjectProperty P145i_left_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P145i_left_by" );
    
    public static final ObjectProperty P146_separated_from = m_model.createObjectProperty( "http://erlangen-crm.org/current/P146_separated_from" );
    
    public static final ObjectProperty P146i_lost_member_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P146i_lost_member_by" );
    
    public static final ObjectProperty P147_curated = m_model.createObjectProperty( "http://erlangen-crm.org/current/P147_curated" );
    
    public static final ObjectProperty P147i_was_curated_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P147i_was_curated_by" );
    
    public static final ObjectProperty P148_has_component = m_model.createObjectProperty( "http://erlangen-crm.org/current/P148_has_component" );
    
    public static final ObjectProperty P148i_is_component_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P148i_is_component_of" );
    
    public static final ObjectProperty P149_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P149_is_identified_by" );
    
    public static final ObjectProperty P149i_identifies = m_model.createObjectProperty( "http://erlangen-crm.org/current/P149i_identifies" );
    
    public static final ObjectProperty P14_carried_out_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P14_carried_out_by" );
    
    public static final ObjectProperty P14i_performed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P14i_performed" );
    
    public static final ObjectProperty P150_defines_typical_parts_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P150_defines_typical_parts_of" );
    
    public static final ObjectProperty P150i_defines_typical_wholes_for = m_model.createObjectProperty( "http://erlangen-crm.org/current/P150i_defines_typical_wholes_for" );
    
    public static final ObjectProperty P151_was_formed_from = m_model.createObjectProperty( "http://erlangen-crm.org/current/P151_was_formed_from" );
    
    public static final ObjectProperty P151i_participated_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P151i_participated_in" );
    
    public static final ObjectProperty P152_has_parent = m_model.createObjectProperty( "http://erlangen-crm.org/current/P152_has_parent" );
    
    public static final ObjectProperty P152i_is_parent_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P152i_is_parent_of" );
    
    public static final ObjectProperty P156_occupies = m_model.createObjectProperty( "http://erlangen-crm.org/current/P156_occupies" );
    
    public static final ObjectProperty P157_is_at_rest_relative_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P157_is_at_rest_relative_to" );
    
    public static final ObjectProperty P157i_provides_reference_space_for = m_model.createObjectProperty( "http://erlangen-crm.org/current/P157i_provides_reference_space_for" );
    
    public static final ObjectProperty P15_was_influenced_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P15_was_influenced_by" );
    
    public static final ObjectProperty P15i_influenced = m_model.createObjectProperty( "http://erlangen-crm.org/current/P15i_influenced" );
    
    public static final ObjectProperty P160_has_temporal_projection = m_model.createObjectProperty( "http://erlangen-crm.org/current/P160_has_temporal_projection" );
    
    public static final ObjectProperty P161_has_spatial_projection = m_model.createObjectProperty( "http://erlangen-crm.org/current/P161_has_spatial_projection" );
    
    public static final ObjectProperty P164_during = m_model.createObjectProperty( "http://erlangen-crm.org/current/P164_during" );
    
    public static final ObjectProperty P164i_was_time_span_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P164i_was_time-span_of" );
    
    public static final ObjectProperty P165_incorporates = m_model.createObjectProperty( "http://erlangen-crm.org/current/P165_incorporates" );
    
    public static final ObjectProperty P165i_is_incorporated_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P165i_is_incorporated_in" );
    
    public static final ObjectProperty P166_was_a_presence_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P166_was_a_presence_of" );
    
    public static final ObjectProperty P166i_had_presence = m_model.createObjectProperty( "http://erlangen-crm.org/current/P166i_had_presence" );
    
    public static final ObjectProperty P167_at = m_model.createObjectProperty( "http://erlangen-crm.org/current/P167_at" );
    
    public static final ObjectProperty P167i_was_place_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P167i_was_place_of" );
    
    public static final ObjectProperty P16_used_specific_object = m_model.createObjectProperty( "http://erlangen-crm.org/current/P16_used_specific_object" );
    
    public static final ObjectProperty P16i_was_used_for = m_model.createObjectProperty( "http://erlangen-crm.org/current/P16i_was_used_for" );
    
    public static final ObjectProperty P17_was_motivated_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P17_was_motivated_by" );
    
    public static final ObjectProperty P17i_motivated = m_model.createObjectProperty( "http://erlangen-crm.org/current/P17i_motivated" );
    
    public static final ObjectProperty P19_was_intended_use_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P19_was_intended_use_of" );
    
    public static final ObjectProperty P19i_was_made_for = m_model.createObjectProperty( "http://erlangen-crm.org/current/P19i_was_made_for" );
    
    public static final ObjectProperty P1_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P1_is_identified_by" );
    
    public static final ObjectProperty P1i_identifies = m_model.createObjectProperty( "http://erlangen-crm.org/current/P1i_identifies" );
    
    public static final ObjectProperty P20_had_specific_purpose = m_model.createObjectProperty( "http://erlangen-crm.org/current/P20_had_specific_purpose" );
    
    public static final ObjectProperty P20i_was_purpose_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P20i_was_purpose_of" );
    
    public static final ObjectProperty P21_had_general_purpose = m_model.createObjectProperty( "http://erlangen-crm.org/current/P21_had_general_purpose" );
    
    public static final ObjectProperty P21i_was_purpose_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P21i_was_purpose_of" );
    
    public static final ObjectProperty P22_transferred_title_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P22_transferred_title_to" );
    
    public static final ObjectProperty P22i_acquired_title_through = m_model.createObjectProperty( "http://erlangen-crm.org/current/P22i_acquired_title_through" );
    
    public static final ObjectProperty P23_transferred_title_from = m_model.createObjectProperty( "http://erlangen-crm.org/current/P23_transferred_title_from" );
    
    public static final ObjectProperty P23i_surrendered_title_through = m_model.createObjectProperty( "http://erlangen-crm.org/current/P23i_surrendered_title_through" );
    
    public static final ObjectProperty P24_transferred_title_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P24_transferred_title_of" );
    
    public static final ObjectProperty P24i_changed_ownership_through = m_model.createObjectProperty( "http://erlangen-crm.org/current/P24i_changed_ownership_through" );
    
    public static final ObjectProperty P25_moved = m_model.createObjectProperty( "http://erlangen-crm.org/current/P25_moved" );
    
    public static final ObjectProperty P25i_moved_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P25i_moved_by" );
    
    public static final ObjectProperty P26_moved_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P26_moved_to" );
    
    public static final ObjectProperty P26i_was_destination_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P26i_was_destination_of" );
    
    public static final ObjectProperty P27_moved_from = m_model.createObjectProperty( "http://erlangen-crm.org/current/P27_moved_from" );
    
    public static final ObjectProperty P27i_was_origin_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P27i_was_origin_of" );
    
    public static final ObjectProperty P28_custody_surrendered_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P28_custody_surrendered_by" );
    
    public static final ObjectProperty P28i_surrendered_custody_through = m_model.createObjectProperty( "http://erlangen-crm.org/current/P28i_surrendered_custody_through" );
    
    public static final ObjectProperty P29_custody_received_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P29_custody_received_by" );
    
    public static final ObjectProperty P29i_received_custody_through = m_model.createObjectProperty( "http://erlangen-crm.org/current/P29i_received_custody_through" );
    
    public static final ObjectProperty P2_has_type = m_model.createObjectProperty( "http://erlangen-crm.org/current/P2_has_type" );
    
    public static final ObjectProperty P2i_is_type_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P2i_is_type_of" );
    
    public static final ObjectProperty P30_transferred_custody_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P30_transferred_custody_of" );
    
    public static final ObjectProperty P30i_custody_transferred_through = m_model.createObjectProperty( "http://erlangen-crm.org/current/P30i_custody_transferred_through" );
    
    public static final ObjectProperty P31_has_modified = m_model.createObjectProperty( "http://erlangen-crm.org/current/P31_has_modified" );
    
    public static final ObjectProperty P31i_was_modified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P31i_was_modified_by" );
    
    public static final ObjectProperty P32_used_general_technique = m_model.createObjectProperty( "http://erlangen-crm.org/current/P32_used_general_technique" );
    
    public static final ObjectProperty P32i_was_technique_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P32i_was_technique_of" );
    
    public static final ObjectProperty P33_used_specific_technique = m_model.createObjectProperty( "http://erlangen-crm.org/current/P33_used_specific_technique" );
    
    public static final ObjectProperty P33i_was_used_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P33i_was_used_by" );
    
    public static final ObjectProperty P34_concerned = m_model.createObjectProperty( "http://erlangen-crm.org/current/P34_concerned" );
    
    public static final ObjectProperty P34i_was_assessed_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P34i_was_assessed_by" );
    
    public static final ObjectProperty P35_has_identified = m_model.createObjectProperty( "http://erlangen-crm.org/current/P35_has_identified" );
    
    public static final ObjectProperty P35i_was_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P35i_was_identified_by" );
    
    public static final ObjectProperty P37_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/current/P37_assigned" );
    
    public static final ObjectProperty P37i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P37i_was_assigned_by" );
    
    public static final ObjectProperty P38_deassigned = m_model.createObjectProperty( "http://erlangen-crm.org/current/P38_deassigned" );
    
    public static final ObjectProperty P38i_was_deassigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P38i_was_deassigned_by" );
    
    public static final ObjectProperty P39_measured = m_model.createObjectProperty( "http://erlangen-crm.org/current/P39_measured" );
    
    public static final ObjectProperty P39i_was_measured_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P39i_was_measured_by" );
    
    public static final ObjectProperty P40_observed_dimension = m_model.createObjectProperty( "http://erlangen-crm.org/current/P40_observed_dimension" );
    
    public static final ObjectProperty P40i_was_observed_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P40i_was_observed_in" );
    
    public static final ObjectProperty P41_classified = m_model.createObjectProperty( "http://erlangen-crm.org/current/P41_classified" );
    
    public static final ObjectProperty P41i_was_classified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P41i_was_classified_by" );
    
    public static final ObjectProperty P42_assigned = m_model.createObjectProperty( "http://erlangen-crm.org/current/P42_assigned" );
    
    public static final ObjectProperty P42i_was_assigned_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P42i_was_assigned_by" );
    
    public static final ObjectProperty P43_has_dimension = m_model.createObjectProperty( "http://erlangen-crm.org/current/P43_has_dimension" );
    
    public static final ObjectProperty P43i_is_dimension_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P43i_is_dimension_of" );
    
    public static final ObjectProperty P44_has_condition = m_model.createObjectProperty( "http://erlangen-crm.org/current/P44_has_condition" );
    
    public static final ObjectProperty P44i_is_condition_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P44i_is_condition_of" );
    
    public static final ObjectProperty P45_consists_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P45_consists_of" );
    
    public static final ObjectProperty P45i_is_incorporated_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P45i_is_incorporated_in" );
    
    public static final ObjectProperty P46_is_composed_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P46_is_composed_of" );
    
    public static final ObjectProperty P46i_forms_part_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P46i_forms_part_of" );
    
    public static final ObjectProperty P48_has_preferred_identifier = m_model.createObjectProperty( "http://erlangen-crm.org/current/P48_has_preferred_identifier" );
    
    public static final ObjectProperty P48i_is_preferred_identifier_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P48i_is_preferred_identifier_of" );
    
    public static final ObjectProperty P49_has_former_or_current_keeper = m_model.createObjectProperty( "http://erlangen-crm.org/current/P49_has_former_or_current_keeper" );
    
    public static final ObjectProperty P49i_is_former_or_current_keeper_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P49i_is_former_or_current_keeper_of" );
    
    public static final ObjectProperty P4_has_time_span = m_model.createObjectProperty( "http://erlangen-crm.org/current/P4_has_time-span" );
    
    public static final ObjectProperty P4i_is_time_span_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P4i_is_time-span_of" );
    
    public static final ObjectProperty P50_has_current_keeper = m_model.createObjectProperty( "http://erlangen-crm.org/current/P50_has_current_keeper" );
    
    public static final ObjectProperty P50i_is_current_keeper_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P50i_is_current_keeper_of" );
    
    public static final ObjectProperty P51_has_former_or_current_owner = m_model.createObjectProperty( "http://erlangen-crm.org/current/P51_has_former_or_current_owner" );
    
    public static final ObjectProperty P51i_is_former_or_current_owner_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P51i_is_former_or_current_owner_of" );
    
    public static final ObjectProperty P52_has_current_owner = m_model.createObjectProperty( "http://erlangen-crm.org/current/P52_has_current_owner" );
    
    public static final ObjectProperty P52i_is_current_owner_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P52i_is_current_owner_of" );
    
    public static final ObjectProperty P53_has_former_or_current_location = m_model.createObjectProperty( "http://erlangen-crm.org/current/P53_has_former_or_current_location" );
    
    public static final ObjectProperty P53i_is_former_or_current_location_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P53i_is_former_or_current_location_of" );
    
    public static final ObjectProperty P54_has_current_permanent_location = m_model.createObjectProperty( "http://erlangen-crm.org/current/P54_has_current_permanent_location" );
    
    public static final ObjectProperty P54i_is_current_permanent_location_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P54i_is_current_permanent_location_of" );
    
    public static final ObjectProperty P55_has_current_location = m_model.createObjectProperty( "http://erlangen-crm.org/current/P55_has_current_location" );
    
    public static final ObjectProperty P55i_currently_holds = m_model.createObjectProperty( "http://erlangen-crm.org/current/P55i_currently_holds" );
    
    public static final ObjectProperty P56_bears_feature = m_model.createObjectProperty( "http://erlangen-crm.org/current/P56_bears_feature" );
    
    public static final ObjectProperty P56i_is_found_on = m_model.createObjectProperty( "http://erlangen-crm.org/current/P56i_is_found_on" );
    
    public static final ObjectProperty P58_has_section_definition = m_model.createObjectProperty( "http://erlangen-crm.org/current/P58_has_section_definition" );
    
    public static final ObjectProperty P58i_defines_section = m_model.createObjectProperty( "http://erlangen-crm.org/current/P58i_defines_section" );
    
    public static final ObjectProperty P59_has_section = m_model.createObjectProperty( "http://erlangen-crm.org/current/P59_has_section" );
    
    public static final ObjectProperty P59i_is_located_on_or_within = m_model.createObjectProperty( "http://erlangen-crm.org/current/P59i_is_located_on_or_within" );
    
    public static final ObjectProperty P5_consists_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P5_consists_of" );
    
    public static final ObjectProperty P5i_forms_part_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P5i_forms_part_of" );
    
    public static final ObjectProperty P62_depicts = m_model.createObjectProperty( "http://erlangen-crm.org/current/P62_depicts" );
    
    public static final ObjectProperty P62i_is_depicted_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P62i_is_depicted_by" );
    
    public static final ObjectProperty P65_shows_visual_item = m_model.createObjectProperty( "http://erlangen-crm.org/current/P65_shows_visual_item" );
    
    public static final ObjectProperty P65i_is_shown_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P65i_is_shown_by" );
    
    public static final ObjectProperty P67_refers_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P67_refers_to" );
    
    public static final ObjectProperty P67i_is_referred_to_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P67i_is_referred_to_by" );
    
    public static final ObjectProperty P68_foresees_use_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P68_foresees_use_of" );
    
    public static final ObjectProperty P68i_use_foreseen_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P68i_use_foreseen_by" );
    
    public static final ObjectProperty P69_has_association_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P69_has_association_with" );
    
    public static final ObjectProperty P69i_is_associated_with = m_model.createObjectProperty( "http://erlangen-crm.org/current/P69i_is_associated_with" );
    
    public static final ObjectProperty P70_documents = m_model.createObjectProperty( "http://erlangen-crm.org/current/P70_documents" );
    
    public static final ObjectProperty P70i_is_documented_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P70i_is_documented_in" );
    
    public static final ObjectProperty P71_lists = m_model.createObjectProperty( "http://erlangen-crm.org/current/P71_lists" );
    
    public static final ObjectProperty P71i_is_listed_in = m_model.createObjectProperty( "http://erlangen-crm.org/current/P71i_is_listed_in" );
    
    public static final ObjectProperty P72_has_language = m_model.createObjectProperty( "http://erlangen-crm.org/current/P72_has_language" );
    
    public static final ObjectProperty P72i_is_language_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P72i_is_language_of" );
    
    public static final ObjectProperty P73_has_translation = m_model.createObjectProperty( "http://erlangen-crm.org/current/P73_has_translation" );
    
    public static final ObjectProperty P73i_is_translation_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P73i_is_translation_of" );
    
    public static final ObjectProperty P74_has_current_or_former_residence = m_model.createObjectProperty( "http://erlangen-crm.org/current/P74_has_current_or_former_residence" );
    
    public static final ObjectProperty P74i_is_current_or_former_residence_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P74i_is_current_or_former_residence_of" );
    
    public static final ObjectProperty P75_possesses = m_model.createObjectProperty( "http://erlangen-crm.org/current/P75_possesses" );
    
    public static final ObjectProperty P75i_is_possessed_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P75i_is_possessed_by" );
    
    public static final ObjectProperty P76_has_contact_point = m_model.createObjectProperty( "http://erlangen-crm.org/current/P76_has_contact_point" );
    
    public static final ObjectProperty P76i_provides_access_to = m_model.createObjectProperty( "http://erlangen-crm.org/current/P76i_provides_access_to" );
    
    public static final ObjectProperty P78_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P78_is_identified_by" );
    
    public static final ObjectProperty P78i_identifies = m_model.createObjectProperty( "http://erlangen-crm.org/current/P78i_identifies" );
    
    public static final ObjectProperty P7_took_place_at = m_model.createObjectProperty( "http://erlangen-crm.org/current/P7_took_place_at" );
    
    public static final ObjectProperty P7i_witnessed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P7i_witnessed" );
    
    public static final ObjectProperty P83_had_at_least_duration = m_model.createObjectProperty( "http://erlangen-crm.org/current/P83_had_at_least_duration" );
    
    public static final ObjectProperty P83i_was_minimum_duration_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P83i_was_minimum_duration_of" );
    
    public static final ObjectProperty P84_had_at_most_duration = m_model.createObjectProperty( "http://erlangen-crm.org/current/P84_had_at_most_duration" );
    
    public static final ObjectProperty P84i_was_maximum_duration_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P84i_was_maximum_duration_of" );
    
    public static final ObjectProperty P86_falls_within = m_model.createObjectProperty( "http://erlangen-crm.org/current/P86_falls_within" );
    
    public static final ObjectProperty P86i_contains = m_model.createObjectProperty( "http://erlangen-crm.org/current/P86i_contains" );
    
    public static final ObjectProperty P87_is_identified_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P87_is_identified_by" );
    
    public static final ObjectProperty P87i_identifies = m_model.createObjectProperty( "http://erlangen-crm.org/current/P87i_identifies" );
    
    public static final ObjectProperty P89_falls_within = m_model.createObjectProperty( "http://erlangen-crm.org/current/P89_falls_within" );
    
    public static final ObjectProperty P89i_contains = m_model.createObjectProperty( "http://erlangen-crm.org/current/P89i_contains" );
    
    public static final ObjectProperty P8_took_place_on_or_within = m_model.createObjectProperty( "http://erlangen-crm.org/current/P8_took_place_on_or_within" );
    
    public static final ObjectProperty P8i_witnessed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P8i_witnessed" );
    
    public static final ObjectProperty P91_has_unit = m_model.createObjectProperty( "http://erlangen-crm.org/current/P91_has_unit" );
    
    public static final ObjectProperty P91i_is_unit_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P91i_is_unit_of" );
    
    public static final ObjectProperty P92_brought_into_existence = m_model.createObjectProperty( "http://erlangen-crm.org/current/P92_brought_into_existence" );
    
    public static final ObjectProperty P92i_was_brought_into_existence_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P92i_was_brought_into_existence_by" );
    
    public static final ObjectProperty P93_took_out_of_existence = m_model.createObjectProperty( "http://erlangen-crm.org/current/P93_took_out_of_existence" );
    
    public static final ObjectProperty P93i_was_taken_out_of_existence_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P93i_was_taken_out_of_existence_by" );
    
    public static final ObjectProperty P94_has_created = m_model.createObjectProperty( "http://erlangen-crm.org/current/P94_has_created" );
    
    public static final ObjectProperty P94i_was_created_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P94i_was_created_by" );
    
    public static final ObjectProperty P95_has_formed = m_model.createObjectProperty( "http://erlangen-crm.org/current/P95_has_formed" );
    
    public static final ObjectProperty P95i_was_formed_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P95i_was_formed_by" );
    
    public static final ObjectProperty P96_by_mother = m_model.createObjectProperty( "http://erlangen-crm.org/current/P96_by_mother" );
    
    public static final ObjectProperty P96i_gave_birth = m_model.createObjectProperty( "http://erlangen-crm.org/current/P96i_gave_birth" );
    
    public static final ObjectProperty P97_from_father = m_model.createObjectProperty( "http://erlangen-crm.org/current/P97_from_father" );
    
    public static final ObjectProperty P97i_was_father_for = m_model.createObjectProperty( "http://erlangen-crm.org/current/P97i_was_father_for" );
    
    public static final ObjectProperty P98_brought_into_life = m_model.createObjectProperty( "http://erlangen-crm.org/current/P98_brought_into_life" );
    
    public static final ObjectProperty P98i_was_born = m_model.createObjectProperty( "http://erlangen-crm.org/current/P98i_was_born" );
    
    public static final ObjectProperty P99_dissolved = m_model.createObjectProperty( "http://erlangen-crm.org/current/P99_dissolved" );
    
    public static final ObjectProperty P99i_was_dissolved_by = m_model.createObjectProperty( "http://erlangen-crm.org/current/P99i_was_dissolved_by" );
    
    public static final ObjectProperty P9_consists_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P9_consists_of" );
    
    public static final ObjectProperty P9i_forms_part_of = m_model.createObjectProperty( "http://erlangen-crm.org/current/P9i_forms_part_of" );
    
    public static final DatatypeProperty P168_place_is_defined_by = m_model.createDatatypeProperty( "http://erlangen-crm.org/current/P168_place_is_defined_by" );
    
    public static final DatatypeProperty P3_has_note = m_model.createDatatypeProperty( "http://erlangen-crm.org/current/P3_has_note" );
    
    public static final DatatypeProperty P57_has_number_of_parts = m_model.createDatatypeProperty( "http://erlangen-crm.org/current/P57_has_number_of_parts" );
    
    public static final DatatypeProperty P79_beginning_is_qualified_by = m_model.createDatatypeProperty( "http://erlangen-crm.org/current/P79_beginning_is_qualified_by" );
    
    public static final DatatypeProperty P80_end_is_qualified_by = m_model.createDatatypeProperty( "http://erlangen-crm.org/current/P80_end_is_qualified_by" );
    
    public static final DatatypeProperty P81_ongoing_throughout = m_model.createDatatypeProperty( "http://erlangen-crm.org/current/P81_ongoing_throughout" );
    
    public static final DatatypeProperty P82_at_some_time_within = m_model.createDatatypeProperty( "http://erlangen-crm.org/current/P82_at_some_time_within" );
    
    public static final DatatypeProperty P90_has_value = m_model.createDatatypeProperty( "http://erlangen-crm.org/current/P90_has_value" );
    
    public static final OntClass E10_Transfer_of_Custody = m_model.createClass( "http://erlangen-crm.org/current/E10_Transfer_of_Custody" );
    
    public static final OntClass E11_Modification = m_model.createClass( "http://erlangen-crm.org/current/E11_Modification" );
    
    public static final OntClass E12_Production = m_model.createClass( "http://erlangen-crm.org/current/E12_Production" );
    
    public static final OntClass E13_Attribute_Assignment = m_model.createClass( "http://erlangen-crm.org/current/E13_Attribute_Assignment" );
    
    public static final OntClass E14_Condition_Assessment = m_model.createClass( "http://erlangen-crm.org/current/E14_Condition_Assessment" );
    
    public static final OntClass E15_Identifier_Assignment = m_model.createClass( "http://erlangen-crm.org/current/E15_Identifier_Assignment" );
    
    public static final OntClass E16_Measurement = m_model.createClass( "http://erlangen-crm.org/current/E16_Measurement" );
    
    public static final OntClass E17_Type_Assignment = m_model.createClass( "http://erlangen-crm.org/current/E17_Type_Assignment" );
    
    public static final OntClass E18_Physical_Thing = m_model.createClass( "http://erlangen-crm.org/current/E18_Physical_Thing" );
    
    public static final OntClass E19_Physical_Object = m_model.createClass( "http://erlangen-crm.org/current/E19_Physical_Object" );
    
    public static final OntClass E1_CRM_Entity = m_model.createClass( "http://erlangen-crm.org/current/E1_CRM_Entity" );
    
    public static final OntClass E20_Biological_Object = m_model.createClass( "http://erlangen-crm.org/current/E20_Biological_Object" );
    
    public static final OntClass E21_Person = m_model.createClass( "http://erlangen-crm.org/current/E21_Person" );
    
    public static final OntClass E22_Man_Made_Object = m_model.createClass( "http://erlangen-crm.org/current/E22_Man-Made_Object" );
    
    public static final OntClass E24_Physical_Man_Made_Thing = m_model.createClass( "http://erlangen-crm.org/current/E24_Physical_Man-Made_Thing" );
    
    public static final OntClass E25_Man_Made_Feature = m_model.createClass( "http://erlangen-crm.org/current/E25_Man-Made_Feature" );
    
    public static final OntClass E26_Physical_Feature = m_model.createClass( "http://erlangen-crm.org/current/E26_Physical_Feature" );
    
    public static final OntClass E27_Site = m_model.createClass( "http://erlangen-crm.org/current/E27_Site" );
    
    public static final OntClass E28_Conceptual_Object = m_model.createClass( "http://erlangen-crm.org/current/E28_Conceptual_Object" );
    
    public static final OntClass E29_Design_or_Procedure = m_model.createClass( "http://erlangen-crm.org/current/E29_Design_or_Procedure" );
    
    public static final OntClass E2_Temporal_Entity = m_model.createClass( "http://erlangen-crm.org/current/E2_Temporal_Entity" );
    
    public static final OntClass E30_Right = m_model.createClass( "http://erlangen-crm.org/current/E30_Right" );
    
    public static final OntClass E31_Document = m_model.createClass( "http://erlangen-crm.org/current/E31_Document" );
    
    public static final OntClass E32_Authority_Document = m_model.createClass( "http://erlangen-crm.org/current/E32_Authority_Document" );
    
    public static final OntClass E33_Linguistic_Object = m_model.createClass( "http://erlangen-crm.org/current/E33_Linguistic_Object" );
    
    public static final OntClass E34_Inscription = m_model.createClass( "http://erlangen-crm.org/current/E34_Inscription" );
    
    public static final OntClass E35_Title = m_model.createClass( "http://erlangen-crm.org/current/E35_Title" );
    
    public static final OntClass E36_Visual_Item = m_model.createClass( "http://erlangen-crm.org/current/E36_Visual_Item" );
    
    public static final OntClass E37_Mark = m_model.createClass( "http://erlangen-crm.org/current/E37_Mark" );
    
    public static final OntClass E38_Image = m_model.createClass( "http://erlangen-crm.org/current/E38_Image" );
    
    public static final OntClass E39_Actor = m_model.createClass( "http://erlangen-crm.org/current/E39_Actor" );
    
    public static final OntClass E3_Condition_State = m_model.createClass( "http://erlangen-crm.org/current/E3_Condition_State" );
    
    public static final OntClass E40_Legal_Body = m_model.createClass( "http://erlangen-crm.org/current/E40_Legal_Body" );
    
    public static final OntClass E41_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E41_Appellation" );
    
    public static final OntClass E42_Identifier = m_model.createClass( "http://erlangen-crm.org/current/E42_Identifier" );
    
    public static final OntClass E44_Place_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E44_Place_Appellation" );
    
    public static final OntClass E45_Address = m_model.createClass( "http://erlangen-crm.org/current/E45_Address" );
    
    public static final OntClass E46_Section_Definition = m_model.createClass( "http://erlangen-crm.org/current/E46_Section_Definition" );
    
    public static final OntClass E47_Spatial_Coordinates = m_model.createClass( "http://erlangen-crm.org/current/E47_Spatial_Coordinates" );
    
    public static final OntClass E48_Place_Name = m_model.createClass( "http://erlangen-crm.org/current/E48_Place_Name" );
    
    public static final OntClass E49_Time_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E49_Time_Appellation" );
    
    public static final OntClass E4_Period = m_model.createClass( "http://erlangen-crm.org/current/E4_Period" );
    
    public static final OntClass E50_Date = m_model.createClass( "http://erlangen-crm.org/current/E50_Date" );
    
    public static final OntClass E51_Contact_Point = m_model.createClass( "http://erlangen-crm.org/current/E51_Contact_Point" );
    
    public static final OntClass E52_Time_Span = m_model.createClass( "http://erlangen-crm.org/current/E52_Time-Span" );
    
    public static final OntClass E53_Place = m_model.createClass( "http://erlangen-crm.org/current/E53_Place" );
    
    public static final OntClass E54_Dimension = m_model.createClass( "http://erlangen-crm.org/current/E54_Dimension" );
    
    public static final OntClass E55_Type = m_model.createClass( "http://erlangen-crm.org/current/E55_Type" );
    
    public static final OntClass E56_Language = m_model.createClass( "http://erlangen-crm.org/current/E56_Language" );
    
    public static final OntClass E57_Material = m_model.createClass( "http://erlangen-crm.org/current/E57_Material" );
    
    public static final OntClass E58_Measurement_Unit = m_model.createClass( "http://erlangen-crm.org/current/E58_Measurement_Unit" );
    
    public static final OntClass E5_Event = m_model.createClass( "http://erlangen-crm.org/current/E5_Event" );
    
    public static final OntClass E63_Beginning_of_Existence = m_model.createClass( "http://erlangen-crm.org/current/E63_Beginning_of_Existence" );
    
    public static final OntClass E64_End_of_Existence = m_model.createClass( "http://erlangen-crm.org/current/E64_End_of_Existence" );
    
    public static final OntClass E65_Creation = m_model.createClass( "http://erlangen-crm.org/current/E65_Creation" );
    
    public static final OntClass E66_Formation = m_model.createClass( "http://erlangen-crm.org/current/E66_Formation" );
    
    public static final OntClass E67_Birth = m_model.createClass( "http://erlangen-crm.org/current/E67_Birth" );
    
    public static final OntClass E68_Dissolution = m_model.createClass( "http://erlangen-crm.org/current/E68_Dissolution" );
    
    public static final OntClass E69_Death = m_model.createClass( "http://erlangen-crm.org/current/E69_Death" );
    
    public static final OntClass E6_Destruction = m_model.createClass( "http://erlangen-crm.org/current/E6_Destruction" );
    
    public static final OntClass E70_Thing = m_model.createClass( "http://erlangen-crm.org/current/E70_Thing" );
    
    public static final OntClass E71_Man_Made_Thing = m_model.createClass( "http://erlangen-crm.org/current/E71_Man-Made_Thing" );
    
    public static final OntClass E72_Legal_Object = m_model.createClass( "http://erlangen-crm.org/current/E72_Legal_Object" );
    
    public static final OntClass E73_Information_Object = m_model.createClass( "http://erlangen-crm.org/current/E73_Information_Object" );
    
    public static final OntClass E74_Group = m_model.createClass( "http://erlangen-crm.org/current/E74_Group" );
    
    public static final OntClass E75_Conceptual_Object_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E75_Conceptual_Object_Appellation" );
    
    public static final OntClass E77_Persistent_Item = m_model.createClass( "http://erlangen-crm.org/current/E77_Persistent_Item" );
    
    public static final OntClass E78_Collection = m_model.createClass( "http://erlangen-crm.org/current/E78_Collection" );
    
    public static final OntClass E79_Part_Addition = m_model.createClass( "http://erlangen-crm.org/current/E79_Part_Addition" );
    
    public static final OntClass E7_Activity = m_model.createClass( "http://erlangen-crm.org/current/E7_Activity" );
    
    public static final OntClass E80_Part_Removal = m_model.createClass( "http://erlangen-crm.org/current/E80_Part_Removal" );
    
    public static final OntClass E81_Transformation = m_model.createClass( "http://erlangen-crm.org/current/E81_Transformation" );
    
    public static final OntClass E82_Actor_Appellation = m_model.createClass( "http://erlangen-crm.org/current/E82_Actor_Appellation" );
    
    public static final OntClass E83_Type_Creation = m_model.createClass( "http://erlangen-crm.org/current/E83_Type_Creation" );
    
    public static final OntClass E84_Information_Carrier = m_model.createClass( "http://erlangen-crm.org/current/E84_Information_Carrier" );
    
    public static final OntClass E85_Joining = m_model.createClass( "http://erlangen-crm.org/current/E85_Joining" );
    
    public static final OntClass E86_Leaving = m_model.createClass( "http://erlangen-crm.org/current/E86_Leaving" );
    
    public static final OntClass E87_Curation_Activity = m_model.createClass( "http://erlangen-crm.org/current/E87_Curation_Activity" );
    
    public static final OntClass E89_Propositional_Object = m_model.createClass( "http://erlangen-crm.org/current/E89_Propositional_Object" );
    
    public static final OntClass E8_Acquisition = m_model.createClass( "http://erlangen-crm.org/current/E8_Acquisition" );
    
    public static final OntClass E90_Symbolic_Object = m_model.createClass( "http://erlangen-crm.org/current/E90_Symbolic_Object" );
    
    public static final OntClass E92_Spacetime_Volume = m_model.createClass( "http://erlangen-crm.org/current/E92_Spacetime_Volume" );
    
    public static final OntClass E93_Presence = m_model.createClass( "http://erlangen-crm.org/current/E93_Presence" );
    
    public static final OntClass E9_Move = m_model.createClass( "http://erlangen-crm.org/current/E9_Move" );
    
}
