/* CVS $Id: $ */
package org.doremus.ontology;

import org.apache.jena.ontology.OntClass;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.ontology.OntModelSpec;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from https://raw.githubusercontent.com/rhizomik/copyrightonto/master/RightsModel/copyrightonto-rightsmodel.ttl 
 * @author Auto-generated by schemagen on 08 Aug 2018 16:44 
 */
public class CRO {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://rhizomik.net/ontologies/copyrightonto#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final OntClass AdaptationRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#AdaptationRight" );
    
    public static final OntClass AttributionRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#AttributionRight" );
    
    public static final OntClass BroadcastersRights = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#BroadcastersRights" );
    
    public static final OntClass BroadcastingRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#BroadcastingRight" );
    
    public static final OntClass CommunicationRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#CommunicationRight" );
    
    public static final OntClass Copyright = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#Copyright" );
    
    public static final OntClass CopyrightExceptions = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#CopyrightExceptions" );
    
    public static final OntClass DisclosureRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#DisclosureRight" );
    
    public static final OntClass DistributionRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#DistributionRight" );
    
    public static final OntClass EconomicRights = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#EconomicRights" );
    
    public static final OntClass EducationOrResearchException = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#EducationOrResearchException" );
    
    public static final OntClass FixationRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#FixationRight" );
    
    public static final OntClass ImportationRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#ImportationRight" );
    
    public static final OntClass IntegrityRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#IntegrityRight" );
    
    public static final OntClass MakingAvailableRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#MakingAvailableRight" );
    
    public static final OntClass MoralRights = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#MoralRights" );
    
    public static final OntClass MotionPictureRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#MotionPictureRight" );
    
    public static final OntClass OfficialActException = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#OfficialActException" );
    
    public static final OntClass ParodyException = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#ParodyException" );
    
    public static final OntClass PerformersRights = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#PerformersRights" );
    
    public static final OntClass PrivateCopyException = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#PrivateCopyException" );
    
    public static final OntClass ProducersRights = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#ProducersRights" );
    
    public static final OntClass PublicPerformanceRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#PublicPerformanceRight" );
    
    public static final OntClass QuotationException = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#QuotationException" );
    
    public static final OntClass RelatedRights = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#RelatedRights" );
    
    public static final OntClass RentalRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#RentalRight" );
    
    public static final OntClass ReportingException = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#ReportingException" );
    
    public static final OntClass ReproductionRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#ReproductionRight" );
    
    public static final OntClass SoundRecordingRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#SoundRecordingRight" );
    
    public static final OntClass TemporaryReproductionException = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#TemporaryReproductionException" );
    
    public static final OntClass TransformationRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#TransformationRight" );
    
    public static final OntClass TranslationRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#TranslationRight" );
    
    public static final OntClass WithdrawalRight = m_model.createClass( "http://rhizomik.net/ontologies/copyrightonto#WithdrawalRight" );
    
}
