/* CVS $Id: $ */
package org.doremus.ontology;
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;

/**
 * Vocabulary definitions from https://raw.githubusercontent.com/DOREMUS-ANR/doremus-ontology/master/doremus.ttl
 * @author Auto-generated by schemagen on 11 ago 2016 15:51
 */
public class MUS {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://data.doremus.org/ontology#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "v0.1";

    public static final ObjectProperty U10_has_order_number = m_model.createObjectProperty( "http://data.doremus.org/ontology#U10_has_order_number" );

    public static final ObjectProperty U10i_is_order_number_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U10i_is_order_number_of" );

    public static final ObjectProperty U11_has_key = m_model.createObjectProperty( "http://data.doremus.org/ontology#U11_has_key" );

    public static final ObjectProperty U11i_is_key_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U11i_is_key_of" );

    public static final ObjectProperty U12_has_genre = m_model.createObjectProperty( "http://data.doremus.org/ontology#U12_has_genre" );

    public static final ObjectProperty U12i_is_genre_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U12i_is_genre_of" );

    public static final ObjectProperty U13_has_intended_casting = m_model.createObjectProperty( "http://data.doremus.org/ontology#U13_has_intended_casting" );

    public static final ObjectProperty U13i_is_intended_casting_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U13i_is_intended_casting_of" );

    public static final ObjectProperty U14_has_intended_tempo = m_model.createObjectProperty( "http://data.doremus.org/ontology#U14_has_intended_tempo" );

    public static final ObjectProperty U14i_is_intended_tempo_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U14i_is_intended_tempo_of" );

    public static final ObjectProperty U15_has_medium_of_performance = m_model.createObjectProperty( "http://data.doremus.org/ontology#U15_has_medium_of_performance" );

    public static final ObjectProperty U15i_is_medium_of_performance_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U15i_is_medium_of_performance_of" );

    public static final ObjectProperty U16_has_catalogue_statement = m_model.createObjectProperty( "http://data.doremus.org/ontology#U16_has_catalogue_statement" );

    public static final ObjectProperty U16_is_catalogue_statement_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U16_is_catalogue_statement_of" );

    public static final ObjectProperty U17_has_opus_statement = m_model.createObjectProperty( "http://data.doremus.org/ontology#U17_has_opus_statement" );

    public static final ObjectProperty U17i_is_opus_statement_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U17i_is_opus_statement_of" );

    public static final ObjectProperty U18_used_medium_of_performance_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U18_used_medium_of_performance_of_type" );

    public static final ObjectProperty U18i_medium_of_performance_was_used_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U18i_medium_of_performance_was_used_in" );

    public static final ObjectProperty U19_has_style = m_model.createObjectProperty( "http://data.doremus.org/ontology#U19_has_style" );

    public static final ObjectProperty U19i_is_style_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U19i_is_style_of" );

    public static final ObjectProperty U1_has_intended_medium_of_performance = m_model.createObjectProperty( "http://data.doremus.org/ontology#U1_has_intended_medium_of_performance" );

    public static final ObjectProperty U1i_is_intended_medium_of_performance_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U1i_is_intended_medium_of_performance_of" );

    public static final ObjectProperty U20_has_music_group_formation = m_model.createObjectProperty( "http://data.doremus.org/ontology#U20_has_music_group_formation" );

    public static final ObjectProperty U20i_is_music_group_formation_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U20i_is_music_group_formation_of" );

    public static final ObjectProperty U21_has_tag = m_model.createObjectProperty( "http://data.doremus.org/ontology#U21_has_tag" );

    public static final ObjectProperty U21i_is_tag_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U21i_is_tag_of" );

    public static final ObjectProperty U22_has_mode = m_model.createObjectProperty( "http://data.doremus.org/ontology#U22_has_mode" );

    public static final ObjectProperty U22i_is_mode_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U22i_is_mode_of" );

    public static final ObjectProperty U23_has_casting_detail = m_model.createObjectProperty( "http://data.doremus.org/ontology#U23_has_casting_detail" );

    public static final ObjectProperty U23i_is_casting_detail_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U23i_is_casting_detail_of" );

    public static final ObjectProperty U25_alternate_casting = m_model.createObjectProperty( "http://data.doremus.org/ontology#U25_alternate_casting" );

    public static final ObjectProperty U26_has_maintained = m_model.createObjectProperty( "http://data.doremus.org/ontology#U26_has_maintained" );

    public static final ObjectProperty U26i_was_maintained_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U26i_was_maintained_by" );

    public static final ObjectProperty U27_performed_character_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U27_performed_character_of" );

    public static final ObjectProperty U27i_character_was_performed_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U27i_character_was_performed_by" );

    public static final ObjectProperty U28_has_intended_tessitura = m_model.createObjectProperty( "http://data.doremus.org/ontology#U28_has_intended_tessitura" );

    public static final ObjectProperty U28i_is_intended_tessitura_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U28i_is_intended_tessitura_of" );

    public static final ObjectProperty U29_edited = m_model.createObjectProperty( "http://data.doremus.org/ontology#U29_edited" );

    public static final ObjectProperty U29i_was_edited_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U29i_was_edited_by" );

    public static final ObjectProperty U2_foresees_use_of_medium_of_performance_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U2_foresees_use_of_medium_of_performance_of_type" );

    public static final ObjectProperty U2i_is_foreseen_type_of_medium_of_performance = m_model.createObjectProperty( "http://data.doremus.org/ontology#U2i_is_foreseen_type_of_medium_of_performance" );

    public static final ObjectProperty U30_created_track = m_model.createObjectProperty( "http://data.doremus.org/ontology#U30_created_track" );

    public static final ObjectProperty U30i_track_was_created_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U30i_track_was_created_by" );

    public static final ObjectProperty U31_had_function_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U31_had_function_of_type" );

    public static final ObjectProperty U31i_is_function_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U31i_is_function_of" );

    public static final ObjectProperty U32_had_responsibility_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U32_had_responsibility_of_type" );

    public static final ObjectProperty U32i_is_responsibility_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U32i_is_responsibility_of" );

    public static final ObjectProperty U35_foresees_function_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U35_foresees_function_of_type" );

    public static final ObjectProperty U35i_is_foreseen_function_type_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U35i_is_foreseen_function_type_of" );

    public static final ObjectProperty U36_foresees_responsibility_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U36_foresees_responsibility_of_type" );

    public static final ObjectProperty U36i_is_foreseen_responsibility_type_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U36i_is_foreseen_responsibility_type_of" );

    public static final ObjectProperty U37_foresees_performing_character = m_model.createObjectProperty( "http://data.doremus.org/ontology#U37_foresees_performing_character" );

    public static final ObjectProperty U37i_is_foreseen_character_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U37i_is_foreseen_character_in" );

    public static final ObjectProperty U38_incorporates_track = m_model.createObjectProperty( "http://data.doremus.org/ontology#U38_incorporates_track" );

    public static final ObjectProperty U38i_track_is_incorporated_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U38i_track_is_incorporated_in" );

    public static final ObjectProperty U39_created_a_realisation_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U39_created_a_realisation_of" );

    public static final ObjectProperty U39i_was_realised_through = m_model.createObjectProperty( "http://data.doremus.org/ontology#U39i_was_realised_through" );

    public static final ObjectProperty U3_forees_specific_medium_of_performance = m_model.createObjectProperty( "http://data.doremus.org/ontology#U3_forees_specific_medium_of_performance" );

    public static final ObjectProperty U3i_is_foreseen_specific_medium_of_performance = m_model.createObjectProperty( "http://data.doremus.org/ontology#U3i_is_foreseen_specific_medium_of_performance" );

    public static final ObjectProperty U40_has_catalogue_name = m_model.createObjectProperty( "http://data.doremus.org/ontology#U40_has_catalogue_name" );

    public static final ObjectProperty U40i_is_catalogue_name_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U40i_is_catalogue_name_of" );

    public static final ObjectProperty U41_has_catalogue_number = m_model.createObjectProperty( "http://data.doremus.org/ontology#U41_has_catalogue_number" );

    public static final ObjectProperty U41i_is_catalogue_number_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U41i_is_catalogue_number_of" );

    public static final ObjectProperty U42_has_opus_number = m_model.createObjectProperty( "http://data.doremus.org/ontology#U42_has_opus_number" );

    public static final ObjectProperty U42i_is_opus_number_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U42i_is_opus_number_of" );

    public static final ObjectProperty U43_has_opus_subnumber = m_model.createObjectProperty( "http://data.doremus.org/ontology#U43_has_opus_subnumber" );

    public static final ObjectProperty U43i_is_opus_subnumber_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U43i_is_opus_subnumber_of" );

    public static final ObjectProperty U44_has_dedication_statement = m_model.createObjectProperty( "http://data.doremus.org/ontology#U44_has_dedication_statement" );

    public static final ObjectProperty U44i_is_dedication_statement_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U44i_is_dedication_statement_of" );

    public static final ObjectProperty U45_is_dedicated_to = m_model.createObjectProperty( "http://data.doremus.org/ontology#U45_is_dedicated_to" );

    public static final ObjectProperty U45i_has_dedication = m_model.createObjectProperty( "http://data.doremus.org/ontology#U45i_has_dedication" );

    public static final ObjectProperty U46_occurred_in_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U46_occurred_in_context" );

    public static final ObjectProperty U46i_was_context_for = m_model.createObjectProperty( "http://data.doremus.org/ontology#U46i_was_context_for" );

    public static final ObjectProperty U4_had_princeps_publication = m_model.createObjectProperty( "http://data.doremus.org/ontology#U4_had_princeps_publication" );

    public static final ObjectProperty U4i_was_princeps_publication_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U4i_was_princeps_publication_of" );

    public static final ObjectProperty U51_has_rhythmic_pattern = m_model.createObjectProperty( "http://data.doremus.org/ontology#U51_has_rhythmic_pattern" );

    public static final ObjectProperty U51i_is_rhythmic_pattern_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U51i_is_rhythmic_pattern_of" );

    public static final ObjectProperty U5_had_premiere = m_model.createObjectProperty( "http://data.doremus.org/ontology#U5_had_premiere" );

    public static final ObjectProperty U5i_was_premiere_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U5i_was_premiere_of" );

    public static final ObjectProperty U6_foresees_actor = m_model.createObjectProperty( "http://data.doremus.org/ontology#U6_foresees_actor" );

    public static final ObjectProperty U6i_is_foreseen_actor_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U6i_is_foreseen_actor_of" );

    public static final ObjectProperty U7_foresees_place_at = m_model.createObjectProperty( "http://data.doremus.org/ontology#U7_foresees_place_at" );

    public static final ObjectProperty U7i_is_foreseen_place_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U7i_is_foreseen_place_of" );

    public static final ObjectProperty U8_foresees_time_span = m_model.createObjectProperty( "http://data.doremus.org/ontology#U8_foresees_time-span" );

    public static final ObjectProperty U8i_is_foreseen_time_span_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U8i_is_foreseen_time-span_of" );

    public static final ObjectProperty U9_specifies_character = m_model.createObjectProperty( "http://data.doremus.org/ontology#U9_specifies_character" );

    public static final ObjectProperty U9i_is_character_specified_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U9i_is_character_specified_by" );

    public static final OntClass M10_Catalogue_Name = m_model.createClass( "http://data.doremus.org/ontology#M10_Catalogue_Name" );

    public static final OntClass M11_Catalogue_Number = m_model.createClass( "http://data.doremus.org/ontology#M11_Catalogue_Number" );

    public static final OntClass M12_Opus_Number = m_model.createClass( "http://data.doremus.org/ontology#M12_Opus_Number" );

    public static final OntClass M13_Opus_Subnumber = m_model.createClass( "http://data.doremus.org/ontology#M13_Opus_Subnumber" );

    public static final OntClass M14_Medium_Of_Performance = m_model.createClass( "http://data.doremus.org/ontology#M14_Medium_Of_Performance" );

    public static final OntClass M15_Dedication = m_model.createClass( "http://data.doremus.org/ontology#M15_Dedication" );

    public static final OntClass M16_Maintenance = m_model.createClass( "http://data.doremus.org/ontology#M16_Maintenance" );

    public static final OntClass M17_Controlled_Access_Point_Creator = m_model.createClass( "http://data.doremus.org/ontology#M17_Controlled_Access_Point_Creator" );

    public static final OntClass M18_Controlled_Access_Point_Denomination = m_model.createClass( "http://data.doremus.org/ontology#M18_Controlled_Access_Point_Denomination" );

    public static final OntClass M19_Style = m_model.createClass( "http://data.doremus.org/ontology#M19_Style" );

    public static final OntClass M1_Catalogue_Statement = m_model.createClass( "http://data.doremus.org/ontology#M1_Catalogue_Statement" );

    public static final OntClass M20_Music_Group_Formation = m_model.createClass( "http://data.doremus.org/ontology#M20_Music_Group_Formation" );

    public static final OntClass M21_Description_Tag = m_model.createClass( "http://data.doremus.org/ontology#M21_Description_Tag" );

    public static final OntClass M22_Mode = m_model.createClass( "http://data.doremus.org/ontology#M22_Mode" );

    public static final OntClass M23_Casting_Detail = m_model.createClass( "http://data.doremus.org/ontology#M23_Casting_Detail" );

    public static final OntClass M24_Track = m_model.createClass( "http://data.doremus.org/ontology#M24_Track" );

    public static final OntClass M25_Foreseen_Activity = m_model.createClass( "http://data.doremus.org/ontology#M25_Foreseen_Activity" );

    public static final OntClass M26_Foreseen_Performance = m_model.createClass( "http://data.doremus.org/ontology#M26_Foreseen_Performance" );

    public static final OntClass M27_Foreseen_Individual_Performance = m_model.createClass( "http://data.doremus.org/ontology#M27_Foreseen_Individual_Performance" );

    public static final OntClass M28_Individual_Performance = m_model.createClass( "http://data.doremus.org/ontology#M28_Individual_Performance" );

    public static final OntClass M29_Editing = m_model.createClass( "http://data.doremus.org/ontology#M29_Editing" );

    public static final OntClass M2_Opus_Statement = m_model.createClass( "http://data.doremus.org/ontology#M2_Opus_Statement" );

    public static final OntClass M30_Tessitura = m_model.createClass( "http://data.doremus.org/ontology#M30_Tessitura" );

    public static final OntClass M31_Actor_Function = m_model.createClass( "http://data.doremus.org/ontology#M31_Actor_Function" );

    public static final OntClass M32_Actor_Responsibility = m_model.createClass( "http://data.doremus.org/ontology#M32_Actor_Responsibility" );

    public static final OntClass M35_Cast_Medium_Of_Performance = m_model.createClass( "http://data.doremus.org/ontology#M35_Cast_Medium_Of_Performance" );

    public static final OntClass M37_Scale = m_model.createClass( "http://data.doremus.org/ontology#M37_Scale" );

    public static final OntClass M38_Rhythmic_Pattern = m_model.createClass( "http://data.doremus.org/ontology#M38_Rhythmic_Pattern" );

    public static final OntClass M39_Editing_Work = m_model.createClass( "http://data.doremus.org/ontology#M39_Editing_Work" );

    public static final OntClass M3_Order_Number = m_model.createClass( "http://data.doremus.org/ontology#M3_Order_Number" );

    public static final OntClass M40_Context = m_model.createClass( "http://data.doremus.org/ontology#M40_Context" );

    public static final OntClass M4_Key = m_model.createClass( "http://data.doremus.org/ontology#M4_Key" );

    public static final OntClass M5_Genre = m_model.createClass( "http://data.doremus.org/ontology#M5_Genre" );

    public static final OntClass M6_Intended_Casting = m_model.createClass( "http://data.doremus.org/ontology#M6_Intended_Casting" );

    public static final OntClass M7_Linguistic_Appellation = m_model.createClass( "http://data.doremus.org/ontology#M7_Linguistic_Appellation" );

    public static final OntClass M8_Intended_Tempo = m_model.createClass( "http://data.doremus.org/ontology#M8_Intended_Tempo" );

    public static final OntClass M9_Derivation_Type = m_model.createClass( "http://data.doremus.org/ontology#M9_Derivation_Type" );

}
