/* CVS $Id: $ */
package org.doremus.ontology;
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;

/**
 * Vocabulary definitions from https://raw.githubusercontent.com/DOREMUS-ANR/doremus-ontology/master/doremus.ttl
 * @author Auto-generated by schemagen on 02 mag 2017 10:40
 */
public class MUS {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://data.doremus.org/ontology#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "v0.1";

    public static final ObjectProperty U10_has_order_number = m_model.createObjectProperty( "http://data.doremus.org/ontology#U10_has_order_number" );

    public static final ObjectProperty U10i_is_order_number_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U10i_is_order_number_of" );

    public static final ObjectProperty U11_has_key = m_model.createObjectProperty( "http://data.doremus.org/ontology#U11_has_key" );

    public static final ObjectProperty U11i_is_key_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U11i_is_key_of" );

    public static final ObjectProperty U12_has_genre = m_model.createObjectProperty( "http://data.doremus.org/ontology#U12_has_genre" );

    public static final ObjectProperty U12i_is_genre_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U12i_is_genre_of" );

    public static final ObjectProperty U13_has_casting = m_model.createObjectProperty( "http://data.doremus.org/ontology#U13_has_casting" );

    public static final ObjectProperty U13i_is_casting_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U13i_is_casting_of" );

    public static final ObjectProperty U14_has_tempo = m_model.createObjectProperty( "http://data.doremus.org/ontology#U14_has_tempo" );

    public static final ObjectProperty U14i_is_tempo_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U14i_is_tempo_of" );

    public static final ObjectProperty U16_has_catalogue_statement = m_model.createObjectProperty( "http://data.doremus.org/ontology#U16_has_catalogue_statement" );

    public static final ObjectProperty U16i_is_catalogue_statement_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U16i_is_catalogue_statement_of" );

    public static final ObjectProperty U17_has_opus_statement = m_model.createObjectProperty( "http://data.doremus.org/ontology#U17_has_opus_statement" );

    public static final ObjectProperty U17i_is_opus_statement_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U17i_is_opus_statement_of" );

    public static final ObjectProperty U18_has_rhythmic_pattern = m_model.createObjectProperty( "http://data.doremus.org/ontology#U18_has_rhythmic_pattern" );

    public static final ObjectProperty U18i_is_rhythmic_pattern_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U18i_is_rhythmic_pattern_of" );

    public static final ObjectProperty U19_has_style = m_model.createObjectProperty( "http://data.doremus.org/ontology#U19_has_style" );

    public static final ObjectProperty U19i_is_style_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U19i_is_style_of" );

    public static final ObjectProperty U1_used_medium_of_performance = m_model.createObjectProperty( "http://data.doremus.org/ontology#U1_used_medium_of_performance" );

    public static final ObjectProperty U1i_medium_of_performance_was_used_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U1i_medium_of_performance_was_used_in" );

    public static final ObjectProperty U20_has_music_group_formation = m_model.createObjectProperty( "http://data.doremus.org/ontology#U20_has_music_group_formation" );

    public static final ObjectProperty U20i_is_music_group_formation_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U20i_is_music_group_formation_of" );

    public static final ObjectProperty U21i_is_tag_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U21i_is_tag_of" );

    public static final ObjectProperty U23_has_casting_detail = m_model.createObjectProperty( "http://data.doremus.org/ontology#U23_has_casting_detail" );

    public static final ObjectProperty U23i_is_casting_detail_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U23i_is_casting_detail_of" );

    public static final ObjectProperty U24_has_award = m_model.createObjectProperty( "http://data.doremus.org/ontology#U24_has_award" );

    public static final ObjectProperty U24i_is_award_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U24i_is_award_of" );

    public static final ObjectProperty U25_has_scale = m_model.createObjectProperty( "http://data.doremus.org/ontology#U25_has_scale" );

    public static final ObjectProperty U25i_is_scale_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U25i_is_scale_of" );

    public static final ObjectProperty U26_has_maintained = m_model.createObjectProperty( "http://data.doremus.org/ontology#U26_has_maintained" );

    public static final ObjectProperty U26i_was_maintained_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U26i_was_maintained_by" );

    public static final ObjectProperty U27_performed_character = m_model.createObjectProperty( "http://data.doremus.org/ontology#U27_performed_character" );

    public static final ObjectProperty U27i_character_was_performed_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U27i_character_was_performed_by" );

    public static final ObjectProperty U28_has_tessitura = m_model.createObjectProperty( "http://data.doremus.org/ontology#U28_has_tessitura" );

    public static final ObjectProperty U28i_is_tessitura_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U28i_is_tessitura_of" );

    public static final ObjectProperty U29_edited = m_model.createObjectProperty( "http://data.doremus.org/ontology#U29_edited" );

    public static final ObjectProperty U29i_was_edited_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U29i_was_edited_by" );

    public static final ObjectProperty U2_foresees_use_of_medium_of_performance_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U2_foresees_use_of_medium_of_performance_of_type" );

    public static final ObjectProperty U2i_is_foreseen_type_of_medium_of_performance_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U2i_is_foreseen_type_of_medium_of_performance_in" );

    public static final ObjectProperty U31_had_function_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U31_had_function_of_type" );

    public static final ObjectProperty U31i_was_function_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U31i_was_function_of" );

    public static final ObjectProperty U32_had_responsibility_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U32_had_responsibility_of_type" );

    public static final ObjectProperty U32i_was_responsibility_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U32i_was_responsibility_of" );

    public static final ObjectProperty U33_has_set_of_characters = m_model.createObjectProperty( "http://data.doremus.org/ontology#U33_has_set_of_characters" );

    public static final ObjectProperty U33i_is_set_of_characters_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U33i_is_set_of_characters_of" );

    public static final ObjectProperty U34_foresees_character = m_model.createObjectProperty( "http://data.doremus.org/ontology#U34_foresees_character" );

    public static final ObjectProperty U34i_is_foreseen_character_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U34i_is_foreseen_character_of" );

    public static final ObjectProperty U35_foresees_function_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U35_foresees_function_of_type" );

    public static final ObjectProperty U35i_is_foreseen_function_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U35i_is_foreseen_function_of" );

    public static final ObjectProperty U36_foresees_responsibility_of_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U36_foresees_responsibility_of_type" );

    public static final ObjectProperty U36i_is_foreseen_responsibility_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U36i_is_foreseen_responsibility_of" );

    public static final ObjectProperty U37_foresees_performing_character = m_model.createObjectProperty( "http://data.doremus.org/ontology#U37_foresees_performing_character" );

    public static final ObjectProperty U37i_is_foreseen_character_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U37i_is_foreseen_character_in" );

    public static final ObjectProperty U38_has_descriptive_expression = m_model.createObjectProperty( "http://data.doremus.org/ontology#U38_has_descriptive_expression" );

    public static final ObjectProperty U38i_is_descriptive_expression_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U38i_is_descriptive_expression_of" );

    public static final ObjectProperty U39_has_tuned = m_model.createObjectProperty( "http://data.doremus.org/ontology#U39_has_tuned" );

    public static final ObjectProperty U39i_was_tuned_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U39i_was_tuned_by" );

    public static final ObjectProperty U3_foresees_specific_medium_of_performance = m_model.createObjectProperty( "http://data.doremus.org/ontology#U3_foresees_specific_medium_of_performance" );

    public static final ObjectProperty U3i_is_foreseen_specific_medium_of_performance_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U3i_is_foreseen_specific_medium_of_performance_in" );

    public static final ObjectProperty U40_has_catalogue_name = m_model.createObjectProperty( "http://data.doremus.org/ontology#U40_has_catalogue_name" );

    public static final ObjectProperty U40i_is_catalogue_name_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U40i_is_catalogue_name_of" );

    public static final ObjectProperty U41_has_catalogue_number = m_model.createObjectProperty( "http://data.doremus.org/ontology#U41_has_catalogue_number" );

    public static final ObjectProperty U41i_is_catalogue_number_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U41i_is_catalogue_number_of" );

    public static final ObjectProperty U42_has_opus_number = m_model.createObjectProperty( "http://data.doremus.org/ontology#U42_has_opus_number" );

    public static final ObjectProperty U42i_is_opus_number_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U42i_is_opus_number_of" );

    public static final ObjectProperty U43_has_opus_subnumber = m_model.createObjectProperty( "http://data.doremus.org/ontology#U43_has_opus_subnumber" );

    public static final ObjectProperty U43i_is_opus_subnumber_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U43i_is_opus_subnumber_of" );

    public static final ObjectProperty U44_has_dedication_statement = m_model.createObjectProperty( "http://data.doremus.org/ontology#U44_has_dedication_statement" );

    public static final ObjectProperty U44i_is_dedication_statement_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U44i_is_dedication_statement_of" );

    public static final ObjectProperty U45_has_metronome_indication = m_model.createObjectProperty( "http://data.doremus.org/ontology#U45_has_metronome_indication" );

    public static final ObjectProperty U45i_is_metronome_indication_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U45i_is_metronome_indication_of" );

    public static final ObjectProperty U46_occurred_in_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U46_occurred_in_context" );

    public static final ObjectProperty U46i_was_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U46i_was_context_of" );

    public static final ObjectProperty U47_has_derivation_type = m_model.createObjectProperty( "http://data.doremus.org/ontology#U47_has_derivation_type" );

    public static final ObjectProperty U47i_is_derivation_type_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U47i_is_derivation_type_of" );

    public static final ObjectProperty U49_created_for_actor = m_model.createObjectProperty( "http://data.doremus.org/ontology#U49_created_for_actor" );

    public static final ObjectProperty U49i_actor_motivated = m_model.createObjectProperty( "http://data.doremus.org/ontology#U49i_actor_motivated" );

    public static final ObjectProperty U4_had_princeps_publication = m_model.createObjectProperty( "http://data.doremus.org/ontology#U4_had_princeps_publication" );

    public static final ObjectProperty U4i_was_princeps_publication_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U4i_was_princeps_publication_of" );

    public static final ObjectProperty U51_is_partial_or_full_recording_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U51_is_partial_or_full_recording_of" );

    public static final ObjectProperty U51i_has_partial_or_full_recording = m_model.createObjectProperty( "http://data.doremus.org/ontology#U51i_has_partial_or_full_recording" );

    public static final ObjectProperty U52_has_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U52_has_context" );

    public static final ObjectProperty U52i_is_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U52i_is_context_of" );

    public static final ObjectProperty U53_has_duration = m_model.createObjectProperty( "http://data.doremus.org/ontology#U53_has_duration" );

    public static final ObjectProperty U53i_is_duration_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U53i_is_duration_of" );

    public static final ObjectProperty U54_is_performed_expression_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U54_is_performed_expression_of" );

    public static final ObjectProperty U54i_has_performed_expression = m_model.createObjectProperty( "http://data.doremus.org/ontology#U54i_has_performed_expression" );

    public static final ObjectProperty U55_incorporates_performed_expression = m_model.createObjectProperty( "http://data.doremus.org/ontology#U55_incorporates_performed_expression" );

    public static final ObjectProperty U55i_performed_expression_is_incorporated_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U55i_performed_expression_is_incorporated_in" );

    public static final ObjectProperty U56_occurred_in_historical_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U56_occurred_in_historical_context" );

    public static final ObjectProperty U56i_was_historical_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U56i_was_historical_context_of" );

    public static final ObjectProperty U57_occurred_in_religious_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U57_occurred_in_religious_context" );

    public static final ObjectProperty U57i_was_religious_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U57i_was_religious_context_of" );

    public static final ObjectProperty U58_has_full_published_recording = m_model.createObjectProperty( "http://data.doremus.org/ontology#U58_has_full_published_recording" );

    public static final ObjectProperty U58i_is_full_published_recording_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U58i_is_full_published_recording_of" );

    public static final ObjectProperty U59_has_partial_published_recording = m_model.createObjectProperty( "http://data.doremus.org/ontology#U59_has_partial_published_recording" );

    public static final ObjectProperty U59i_is_partial_published_recording_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U59i_is_partial_published_recording_of" );

    public static final ObjectProperty U5_had_premiere = m_model.createObjectProperty( "http://data.doremus.org/ontology#U5_had_premiere" );

    public static final ObjectProperty U5i_was_premiere_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U5i_was_premiere_of" );

    public static final ObjectProperty U60_occurred_in_cultural_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U60_occurred_in_cultural_context" );

    public static final ObjectProperty U60i_was_cultural_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U60i_was_cultural_context_of" );

    public static final ObjectProperty U61_occurred_in_geographical_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U61_occurred_in_geographical_context" );

    public static final ObjectProperty U61i_was_geographical_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U61i_was_geographical_context_of" );

    public static final ObjectProperty U62_has_form = m_model.createObjectProperty( "http://data.doremus.org/ontology#U62_has_form" );

    public static final ObjectProperty U62i_is_form_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U62i_is_form_of" );

    public static final ObjectProperty U63_has_religious_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U63_has_religious_context" );

    public static final ObjectProperty U63i_is_religious_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U63i_is_religious_context_of" );

    public static final ObjectProperty U64_has_cultural_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U64_has_cultural_context" );

    public static final ObjectProperty U64i_is_cultural_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U64i_is_cultural_context_of" );

    public static final ObjectProperty U65_has_geographical_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U65_has_geographical_context" );

    public static final ObjectProperty U65i_is_geographical_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U65i_is_geographical_context_of" );

    public static final ObjectProperty U66_has_historical_context = m_model.createObjectProperty( "http://data.doremus.org/ontology#U66_has_historical_context" );

    public static final ObjectProperty U66i_is_historical_context_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U66i_is_historical_context_of" );

    public static final ObjectProperty U67_has_subtitle = m_model.createObjectProperty( "http://data.doremus.org/ontology#U67_has_subtitle" );

    public static final ObjectProperty U67i_is_subtitle_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U67i_is_subtitle_of" );

    public static final ObjectProperty U68_has_variant_title = m_model.createObjectProperty( "http://data.doremus.org/ontology#U68_has_variant_title" );

    public static final ObjectProperty U68i_is_variant_title_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U68i_is_variant_title_of" );

    public static final ObjectProperty U69_has_WoO_number = m_model.createObjectProperty( "http://data.doremus.org/ontology#U69_has_WoO_number" );

    public static final ObjectProperty U69i_is_WoO_number_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U69i_is_WoO_number_of" );

    public static final ObjectProperty U6_foresees_actor = m_model.createObjectProperty( "http://data.doremus.org/ontology#U6_foresees_actor" );

    public static final ObjectProperty U6i_is_foreseen_actor_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U6i_is_foreseen_actor_of" );

    public static final ObjectProperty U70_has_title = m_model.createObjectProperty( "http://data.doremus.org/ontology#U70_has_title" );

    public static final ObjectProperty U70i_is_title_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U70i_is_title_of" );

    public static final ObjectProperty U71_has_uniform_music_title = m_model.createObjectProperty( "http://data.doremus.org/ontology#U71_has_uniform_music_title" );

    public static final ObjectProperty U71i_is_uniform_music_title_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U71i_is_uniform_music_title_of" );

    public static final ObjectProperty U73_is_derivative_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U73_is_derivative_of" );

    public static final ObjectProperty U73i_has_derivative = m_model.createObjectProperty( "http://data.doremus.org/ontology#U73i_has_derivative" );

    public static final ObjectProperty U74_cited = m_model.createObjectProperty( "http://data.doremus.org/ontology#U74_cited" );

    public static final ObjectProperty U74i_was_cited_by = m_model.createObjectProperty( "http://data.doremus.org/ontology#U74i_was_cited_by" );

    public static final ObjectProperty U75_has_harmonic_structure = m_model.createObjectProperty( "http://data.doremus.org/ontology#U75_has_harmonic_structure" );

    public static final ObjectProperty U75i_is_harmonic_structure_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U75i_is_harmonic_structure_of" );

    public static final ObjectProperty U76_has_WoO_subnumber = m_model.createObjectProperty( "http://data.doremus.org/ontology#U76_has_WoO_subnumber" );

    public static final ObjectProperty U76i_is_WoO_subnumber_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U76i_is_WoO_subnumber_of" );

    public static final ObjectProperty U77_foresees_performing_plan = m_model.createObjectProperty( "http://data.doremus.org/ontology#U77_foresees_performing_plan" );

    public static final ObjectProperty U77i_is_foreseen_plan_in = m_model.createObjectProperty( "http://data.doremus.org/ontology#U77i_is_foreseen_plan_in" );

    public static final ObjectProperty U7_foresees_place_at = m_model.createObjectProperty( "http://data.doremus.org/ontology#U7_foresees_place_at" );

    public static final ObjectProperty U7i_is_foreseen_place_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U7i_is_foreseen_place_of" );

    public static final ObjectProperty U8_foresees_time_span = m_model.createObjectProperty( "http://data.doremus.org/ontology#U8_foresees_time_span" );

    public static final ObjectProperty U8i_is_foreseen_time_span_of = m_model.createObjectProperty( "http://data.doremus.org/ontology#U8i_is_foreseen_time_span_of" );

    public static final DatatypeProperty U15_has_history = m_model.createDatatypeProperty( "http://data.doremus.org/ontology#U15_has_history" );

    public static final DatatypeProperty U30_foresees_quantity_of_mop = m_model.createDatatypeProperty( "http://data.doremus.org/ontology#U30_foresees_quantity_of_mop" );

    public static final DatatypeProperty U48_foresees_quantity_of_actors = m_model.createDatatypeProperty( "http://data.doremus.org/ontology#U48_foresees_quantity_of_actors" );

    public static final DatatypeProperty U72_has_title_note = m_model.createDatatypeProperty( "http://data.doremus.org/ontology#U72_has_title_note" );

    public static final DatatypeProperty U9_has_quantity = m_model.createDatatypeProperty( "http://data.doremus.org/ontology#U9_has_quantity" );

    public static final OntClass M10_Catalogue_Name = m_model.createClass( "http://data.doremus.org/ontology#M10_Catalogue_Name" );

    public static final OntClass M11_Catalogue_Number = m_model.createClass( "http://data.doremus.org/ontology#M11_Catalogue_Number" );

    public static final OntClass M12_Opus_Number = m_model.createClass( "http://data.doremus.org/ontology#M12_Opus_Number" );

    public static final OntClass M13_Opus_Subnumber = m_model.createClass( "http://data.doremus.org/ontology#M13_Opus_Subnumber" );

    public static final OntClass M14_Medium_Of_Performance = m_model.createClass( "http://data.doremus.org/ontology#M14_Medium_Of_Performance" );

    public static final OntClass M15_Dedication_Statement = m_model.createClass( "http://data.doremus.org/ontology#M15_Dedication_Statement" );

    public static final OntClass M16_Maintenance = m_model.createClass( "http://data.doremus.org/ontology#M16_Maintenance" );

    public static final OntClass M17_Controlled_Access_Point_Creator = m_model.createClass( "http://data.doremus.org/ontology#M17_Controlled_Access_Point_Creator" );

    public static final OntClass M18_Controlled_Access_Point_Denomination = m_model.createClass( "http://data.doremus.org/ontology#M18_Controlled_Access_Point_Denomination" );

    public static final OntClass M19_Style = m_model.createClass( "http://data.doremus.org/ontology#M19_Style" );

    public static final OntClass M1_Catalogue_Statement = m_model.createClass( "http://data.doremus.org/ontology#M1_Catalogue_Statement" );

    public static final OntClass M20_Music_Group_Formation = m_model.createClass( "http://data.doremus.org/ontology#M20_Music_Group_Formation" );

    public static final OntClass M21_Harmonic_Structure = m_model.createClass( "http://data.doremus.org/ontology#M21_Harmonic_Structure" );

    public static final OntClass M22_Form = m_model.createClass( "http://data.doremus.org/ontology#M22_Form" );

    public static final OntClass M23_Casting_Detail = m_model.createClass( "http://data.doremus.org/ontology#M23_Casting_Detail" );

    public static final OntClass M24_Track = m_model.createClass( "http://data.doremus.org/ontology#M24_Track" );

    public static final OntClass M25_Foreseen_Activity = m_model.createClass( "http://data.doremus.org/ontology#M25_Foreseen_Activity" );

    public static final OntClass M26_Foreseen_Performance = m_model.createClass( "http://data.doremus.org/ontology#M26_Foreseen_Performance" );

    public static final OntClass M27_Foreseen_Individual_Performance = m_model.createClass( "http://data.doremus.org/ontology#M27_Foreseen_Individual_Performance" );

    public static final OntClass M28_Individual_Performance = m_model.createClass( "http://data.doremus.org/ontology#M28_Individual_Performance" );

    public static final OntClass M29_Editing = m_model.createClass( "http://data.doremus.org/ontology#M29_Editing" );

    public static final OntClass M2_Opus_Statement = m_model.createClass( "http://data.doremus.org/ontology#M2_Opus_Statement" );

    public static final OntClass M30_Tessitura = m_model.createClass( "http://data.doremus.org/ontology#M30_Tessitura" );

    public static final OntClass M31_Actor_Function = m_model.createClass( "http://data.doremus.org/ontology#M31_Actor_Function" );

    public static final OntClass M32_Actor_Responsibility = m_model.createClass( "http://data.doremus.org/ontology#M32_Actor_Responsibility" );

    public static final OntClass M33_Set_of_Characters = m_model.createClass( "http://data.doremus.org/ontology#M33_Set_of_Characters" );

    public static final OntClass M34_Award_Assignment = m_model.createClass( "http://data.doremus.org/ontology#M34_Award_Assignment" );

    public static final OntClass M35_Representative_Publication_Assignment = m_model.createClass( "http://data.doremus.org/ontology#M35_Representative_Publication_Assignment" );

    public static final OntClass M36_Award = m_model.createClass( "http://data.doremus.org/ontology#M36_Award" );

    public static final OntClass M37_Music_Scale = m_model.createClass( "http://data.doremus.org/ontology#M37_Music_Scale" );

    public static final OntClass M38_Rhythmic_Pattern = m_model.createClass( "http://data.doremus.org/ontology#M38_Rhythmic_Pattern" );

    public static final OntClass M39_Derivation_Type_Assignment = m_model.createClass( "http://data.doremus.org/ontology#M39_Derivation_Type_Assignment" );

    public static final OntClass M3_Order_Number = m_model.createClass( "http://data.doremus.org/ontology#M3_Order_Number" );

    public static final OntClass M40_Context = m_model.createClass( "http://data.doremus.org/ontology#M40_Context" );

    public static final OntClass M41_Metronome_Indication = m_model.createClass( "http://data.doremus.org/ontology#M41_Metronome_Indication" );

    public static final OntClass M42_Performed_Expression_Creation = m_model.createClass( "http://data.doremus.org/ontology#M42_Performed_Expression_Creation" );

    public static final OntClass M43_Performed_Expression = m_model.createClass( "http://data.doremus.org/ontology#M43_Performed_Expression" );

    public static final OntClass M44_Performed_Work = m_model.createClass( "http://data.doremus.org/ontology#M44_Performed_Work" );

    public static final OntClass M45_Descriptive_Expression_Assignment = m_model.createClass( "http://data.doremus.org/ontology#M45_Descriptive_Expression_Assignment" );

    public static final OntClass M46_Set_of_Tracks = m_model.createClass( "http://data.doremus.org/ontology#M46_Set_of_Tracks" );

    public static final OntClass M47_WoO_Number = m_model.createClass( "http://data.doremus.org/ontology#M47_WoO_Number" );

    public static final OntClass M48_WoO_Subnumber = m_model.createClass( "http://data.doremus.org/ontology#M48_WoO_Subnumber" );

    public static final OntClass M4_Key = m_model.createClass( "http://data.doremus.org/ontology#M4_Key" );

    public static final OntClass M5_Genre = m_model.createClass( "http://data.doremus.org/ontology#M5_Genre" );

    public static final OntClass M6_Casting = m_model.createClass( "http://data.doremus.org/ontology#M6_Casting" );

    public static final OntClass M7_Linguistic_Appellation = m_model.createClass( "http://data.doremus.org/ontology#M7_Linguistic_Appellation" );

    public static final OntClass M8_Tempo = m_model.createClass( "http://data.doremus.org/ontology#M8_Tempo" );

    public static final OntClass M9_Derivation_Type = m_model.createClass( "http://data.doremus.org/ontology#M9_Derivation_Type" );

}
