/* CVS $Id: $ */
package org.doremus.ontology;
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;

/**
 * Vocabulary definitions from https://raw.githubusercontent.com/w3c/sdw/gh-pages/time/rdf/time.ttl
 * @author Auto-generated by schemagen on 08 set 2017 18:18
 */
public class Time {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2006/time#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    public static final ObjectProperty after = m_model.createObjectProperty( "http://www.w3.org/2006/time#after" );

    public static final ObjectProperty before = m_model.createObjectProperty( "http://www.w3.org/2006/time#before" );

    public static final ObjectProperty dayOfWeek = m_model.createObjectProperty( "http://www.w3.org/2006/time#dayOfWeek" );

    public static final ObjectProperty days = m_model.createObjectProperty( "http://www.w3.org/2006/time#days" );

    public static final ObjectProperty hasBeginning = m_model.createObjectProperty( "http://www.w3.org/2006/time#hasBeginning" );

    public static final ObjectProperty hasDateTimeDescription = m_model.createObjectProperty( "http://www.w3.org/2006/time#hasDateTimeDescription" );

    public static final ObjectProperty hasDuration = m_model.createObjectProperty( "http://www.w3.org/2006/time#hasDuration" );

    public static final ObjectProperty hasDurationDescription = m_model.createObjectProperty( "http://www.w3.org/2006/time#hasDurationDescription" );

    public static final ObjectProperty hasEnd = m_model.createObjectProperty( "http://www.w3.org/2006/time#hasEnd" );

    public static final ObjectProperty hasTRS = m_model.createObjectProperty( "http://www.w3.org/2006/time#hasTRS" );

    public static final ObjectProperty hasTemporalDuration = m_model.createObjectProperty( "http://www.w3.org/2006/time#hasTemporalDuration" );

    public static final ObjectProperty hasTime = m_model.createObjectProperty( "http://www.w3.org/2006/time#hasTime" );

    public static final ObjectProperty hours = m_model.createObjectProperty( "http://www.w3.org/2006/time#hours" );

    public static final ObjectProperty inDateTime = m_model.createObjectProperty( "http://www.w3.org/2006/time#inDateTime" );

    public static final ObjectProperty inTemporalPosition = m_model.createObjectProperty( "http://www.w3.org/2006/time#inTemporalPosition" );

    public static final ObjectProperty inTimePosition = m_model.createObjectProperty( "http://www.w3.org/2006/time#inTimePosition" );

    public static final ObjectProperty inside = m_model.createObjectProperty( "http://www.w3.org/2006/time#inside" );

    public static final ObjectProperty intervalAfter = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalAfter" );

    public static final ObjectProperty intervalBefore = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalBefore" );

    public static final ObjectProperty intervalContains = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalContains" );

    public static final ObjectProperty intervalDisjoint = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalDisjoint" );

    public static final ObjectProperty intervalDuring = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalDuring" );

    public static final ObjectProperty intervalEquals = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalEquals" );

    public static final ObjectProperty intervalFinishedBy = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalFinishedBy" );

    public static final ObjectProperty intervalFinishes = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalFinishes" );

    public static final ObjectProperty intervalIn = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalIn" );

    public static final ObjectProperty intervalMeets = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalMeets" );

    public static final ObjectProperty intervalMetBy = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalMetBy" );

    public static final ObjectProperty intervalOverlappedBy = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalOverlappedBy" );

    public static final ObjectProperty intervalOverlaps = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalOverlaps" );

    public static final ObjectProperty intervalStartedBy = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalStartedBy" );

    public static final ObjectProperty intervalStarts = m_model.createObjectProperty( "http://www.w3.org/2006/time#intervalStarts" );

    public static final ObjectProperty minutes = m_model.createObjectProperty( "http://www.w3.org/2006/time#minutes" );

    public static final ObjectProperty monthOfYear = m_model.createObjectProperty( "http://www.w3.org/2006/time#monthOfYear" );

    public static final ObjectProperty months = m_model.createObjectProperty( "http://www.w3.org/2006/time#months" );

    public static final ObjectProperty seconds = m_model.createObjectProperty( "http://www.w3.org/2006/time#seconds" );

    public static final ObjectProperty timeZone = m_model.createObjectProperty( "http://www.w3.org/2006/time#timeZone" );

    public static final ObjectProperty unitType = m_model.createObjectProperty( "http://www.w3.org/2006/time#unitType" );

    public static final ObjectProperty weeks = m_model.createObjectProperty( "http://www.w3.org/2006/time#weeks" );

    public static final ObjectProperty years = m_model.createObjectProperty( "http://www.w3.org/2006/time#years" );

    public static final DatatypeProperty day = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#day" );

    public static final DatatypeProperty dayOfYear = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#dayOfYear" );

    public static final DatatypeProperty hasXSDDuration = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#hasXSDDuration" );

    public static final DatatypeProperty hour = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#hour" );

    public static final DatatypeProperty inXSDDate = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#inXSDDate" );

    public static final DatatypeProperty inXSDDateTime = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#inXSDDateTime" );

    public static final DatatypeProperty inXSDDateTimeStamp = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#inXSDDateTimeStamp" );

    public static final DatatypeProperty inXSDgYear = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#inXSDgYear" );

    public static final DatatypeProperty inXSDgYearMonth = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#inXSDgYearMonth" );

    public static final DatatypeProperty minute = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#minute" );

    public static final DatatypeProperty month = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#month" );

    public static final DatatypeProperty nominalPosition = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#nominalPosition" );

    public static final DatatypeProperty numericDuration = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#numericDuration" );

    public static final DatatypeProperty numericPosition = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#numericPosition" );

    public static final DatatypeProperty second = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#second" );

    public static final DatatypeProperty week = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#week" );

    public static final DatatypeProperty xsdDateTime = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#xsdDateTime" );

    public static final DatatypeProperty year = m_model.createDatatypeProperty( "http://www.w3.org/2006/time#year" );

    public static final OntClass DateTimeDescription = m_model.createClass( "http://www.w3.org/2006/time#DateTimeDescription" );

    public static final OntClass DateTimeInterval = m_model.createClass( "http://www.w3.org/2006/time#DateTimeInterval" );

    public static final OntClass DayOfWeek = m_model.createClass( "http://www.w3.org/2006/time#DayOfWeek" );

    public static final OntClass Duration = m_model.createClass( "http://www.w3.org/2006/time#Duration" );

    public static final OntClass DurationDescription = m_model.createClass( "http://www.w3.org/2006/time#DurationDescription" );

    public static final OntClass GeneralDateTimeDescription = m_model.createClass( "http://www.w3.org/2006/time#GeneralDateTimeDescription" );

    public static final OntClass GeneralDurationDescription = m_model.createClass( "http://www.w3.org/2006/time#GeneralDurationDescription" );

    public static final OntClass Instant = m_model.createClass( "http://www.w3.org/2006/time#Instant" );

    public static final OntClass Interval = m_model.createClass( "http://www.w3.org/2006/time#Interval" );

    public static final OntClass January = m_model.createClass( "http://www.w3.org/2006/time#January" );

    public static final OntClass MonthOfYear = m_model.createClass( "http://www.w3.org/2006/time#MonthOfYear" );

    public static final OntClass ProperInterval = m_model.createClass( "http://www.w3.org/2006/time#ProperInterval" );

    public static final OntClass TRS = m_model.createClass( "http://www.w3.org/2006/time#TRS" );

    public static final OntClass TemporalDuration = m_model.createClass( "http://www.w3.org/2006/time#TemporalDuration" );

    public static final OntClass TemporalEntity = m_model.createClass( "http://www.w3.org/2006/time#TemporalEntity" );

    public static final OntClass TemporalPosition = m_model.createClass( "http://www.w3.org/2006/time#TemporalPosition" );

    public static final OntClass TemporalUnit = m_model.createClass( "http://www.w3.org/2006/time#TemporalUnit" );

    public static final OntClass TimePosition = m_model.createClass( "http://www.w3.org/2006/time#TimePosition" );

    public static final OntClass TimeZone = m_model.createClass( "http://www.w3.org/2006/time#TimeZone" );

    public static final OntClass Year = m_model.createClass( "http://www.w3.org/2006/time#Year" );

    public static final Individual Gregorian = m_model.createIndividual( "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian", m_model.createClass( "http://www.w3.org/2002/07/owl#Thing" ) );

    public static final Individual Friday = m_model.createIndividual( "http://www.w3.org/2006/time#Friday", DayOfWeek );

    public static final Individual Monday = m_model.createIndividual( "http://www.w3.org/2006/time#Monday", DayOfWeek );

    public static final Individual Saturday = m_model.createIndividual( "http://www.w3.org/2006/time#Saturday", DayOfWeek );

    public static final Individual Sunday = m_model.createIndividual( "http://www.w3.org/2006/time#Sunday", DayOfWeek );

    public static final Individual Thursday = m_model.createIndividual( "http://www.w3.org/2006/time#Thursday", DayOfWeek );

    public static final Individual Tuesday = m_model.createIndividual( "http://www.w3.org/2006/time#Tuesday", DayOfWeek );

    public static final Individual Wednesday = m_model.createIndividual( "http://www.w3.org/2006/time#Wednesday", DayOfWeek );

    public static final Individual unitDay = m_model.createIndividual( "http://www.w3.org/2006/time#unitDay", TemporalUnit );

    public static final Individual unitHour = m_model.createIndividual( "http://www.w3.org/2006/time#unitHour", TemporalUnit );

    public static final Individual unitMinute = m_model.createIndividual( "http://www.w3.org/2006/time#unitMinute", TemporalUnit );

    public static final Individual unitMonth = m_model.createIndividual( "http://www.w3.org/2006/time#unitMonth", TemporalUnit );

    public static final Individual unitSecond = m_model.createIndividual( "http://www.w3.org/2006/time#unitSecond", TemporalUnit );

    public static final Individual unitWeek = m_model.createIndividual( "http://www.w3.org/2006/time#unitWeek", TemporalUnit );

    public static final Individual unitYear = m_model.createIndividual( "http://www.w3.org/2006/time#unitYear", TemporalUnit );

    public static final Resource generalDay = m_model.createResource( "http://www.w3.org/2006/time#generalDay" );

    public static final Resource generalMonth = m_model.createResource( "http://www.w3.org/2006/time#generalMonth" );

    public static final Resource generalYear = m_model.createResource( "http://www.w3.org/2006/time#generalYear" );

}
